### ISSUE TITLE
Setup base plugin loader

### ISSUE THREAD

**Issue by modemlooper** [buddypress/BP-REST#1]
This could be merged should prolly structure based on current BP core plugin. 

    buddypress/bp-activity/bp-activity-rest.php
or 
    
    buddypress/bp-activity/bp-rest/bp-activity-endpoints.php

**Comment by slaFFik** [comment]
+1 for `buddypress/bp-activity/bp-activity-rest.php`

**Comment by modemlooper** [comment]
set up here in this fork https://github.com/modemlooper/BP-REST, I was looking though the bp plugin and the rss feed class is in bp-acitivty/classes so I thought that might be a good location for file

**Comment by Mamaduka** [comment]
@modemlooper I like structure in your fork. Also think that we don't need `class-bp-rest-loader.php` and base singleton class. We should simply initialize class in main plugin file, similar to WP REST API plugin.

Probably you should also get rid of front-end assets manager files and assets dir.

**Comment by modemlooper** [comment]
the loader is only for this plugin that file will not be in core

**Comment by BronsonQuick** [comment]
@modemlooper Great work so far! I'm +1 on `buddypress/bp-activity/bp-activity-rest.php` for the folder structure.

I also agree regarding not needing a singleton and stripping out the frontend assets folder. Ryan McCue recommended the following https://github.com/BronsonQuick/BP-API/blob/master/bp-rest-api.php to me.

**Comment by modemlooper** [comment]
strip away! the assets are from WDS plugin generator.

**Comment by paulgibbs** [comment]
This looks like it's sort-of been done since the ticket was made, so I'll close it down.
