### ISSUE TITLE
Can we make primary_id and secondary_id accept an array of values?

### ISSUE THREAD

**Issue by tannerm** [buddypress/BP-REST#106]
https://github.com/buddypress/BP-REST/blob/master/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L1345

`bp_activity_get()` accepts an array for `primary_id` and `secondary_id` but the schema for the API is converting the arrays to integers. Can this be updated to allow for arrays for these parameters?

**Comment by renatonascalves** [comment]
This was added this way to allow easier filtering of which value of the `filter` args was being added.

**Comment by tannerm** [comment]
@renatonascalves I am trying to get activity for multiple groups (thereby needing multiple primary_id's). Are you saying that there isn't a way to do this through the API? It's ok if that is the case... I can filter the schema for my install, just wanted to make sure I understand correctly.

**Comment by tannerm** [comment]
@renatonascalves super, thanks!

**Comment by tannerm** [comment]
@renatonascalves thanks so much!

Quick question. Why do you use `current` on [line 139](https://github.com/buddypress/BP-REST/blob/54105666ba19aaf804cc6279ddfcdeb32c53126e/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L139)? Don't we want to verify all attached `primary_id`s?

**Comment by renatonascalves** [comment]
@tannerm This is for the `show_hidden` method. This is not related to the `primary_id` args.

**Comment by tannerm** [comment]
@renatonascalves right, but isn't the point of `show_hidden` to check the associated group(s) to see if the current user is able to view them?

**Comment by tannerm** [comment]
@renatonascalves I extended this API endpoint and this is how I'm handling it: https://github.com/StudyChurch/studychurch/blob/release/2.0/inc/API/Activity.php#L90

Probably a little too open and should verify that the user belongs to ALL groups before granting access to hidden activity.

**Comment by renatonascalves** [comment]
@tannerm Here are my thoughts on that code:

The code as it is now, will invalidade possible group item ids. Only the last one item id will be taken into consideration, as the `foreach` loop won't work for the ones in the beginning.

Something to understand is that what we are doing here is kind of hack, as the `bp_activity_get`  function isn't respossible for deciding if a user has access or not to see the group items you are fetching.

So I'd argue it will be very hard to accomodate all scenarios, including yours out of the box.

What you can do is: after we merge #104, you can filter the args to remove groups the user has not access to.

But in regard to the current implementation, I don't think there is a major problem with it. Maybe apart from the fact we should remove this hidden method as it might cause confusion to people thinking it is the `bp_activity_get` job to take care of that, which it isn't.

**Comment by tannerm** [comment]
Thanks @renatonascalves! I'm not concerned about this for me, the api requests that I'm making are hard coded to include only groups that the user is a member of. I was more concerned, like you are saying, that  `show_hidden` could return a false positive if the request includes groups that the user is not a member of. Again, not something I'm concerned about for my install, just a thought I had as I was working on things last night (and putting my poorly written hack together :P).

I haven't dug into `bg_activity_get` recently, but assumed that it does a check for hidden activity. If that is the case then we may just be able to get rid of the `show_hidden` function. Anyway... sounds like we are on the same page.

**Comment by tannerm** [comment]
@renatonascalves sounds good!

I hope the feedback is helpful and not just annoying. :P I sure appreciate what you are doing here, it's helping out a ton with our product we are building. I'll send you a link once we get it up and running in case you are interested to try it. It's a Vuejs front end that uses the BP API.
