### ISSUE TITLE
`can_see()` for 'edit' context vs update item permission checks?

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#108]
This may be just a question for clarification from @renatonascalves rather than a bug report.

In https://github.com/buddypress/BP-REST/blob/551da0dd50cbde89a2816a8551409b53534548d6/includes/bp-groups/classes/class-bp-rest-groups-endpoint.php#L210 you've got two calls to `can_see()`: one for the default context, and one for the `edit` context. My question is: in what situation would you call `GET /groups/123` in the 'edit' context? What exactly is the 'edit' context - does it specific refer to the Dashboard?

**Comment by boonebgorges** [comment]
Cool - this helps me to understand the purpose of the context (even if we're not really using it at the moment). But I'm still unclear on why we need to do the separate `can_see()` check for this. Is the issue that someone might request a *specific field* in one context that is not available in that context? Like, maybe `user_email` in the user context would not be available for `view`, but if you pass `user_email` as one of the `fields`, then we throw an error?

**Comment by renatonascalves** [comment]
@boonebgorges No! See here: https://github.com/buddypress/BP-REST/blob/551da0dd50cbde89a2816a8551409b53534548d6/includes/bp-groups/classes/class-bp-rest-groups-endpoint.php#L526-L546

There we are showing those fields only for people that can see the `edit` context. They are not available for people who can't see them.

**Comment by boonebgorges** [comment]
Yes, but how does this relate to the `can_see()` check?

**Comment by renatonascalves** [comment]
The first one verifies a normal context, the second one verifies the other one, the `edit` context, and sends a different `WP_Error`.

**Comment by renatonascalves** [comment]
@boonebgorges Let me try to say in another way.

For me, the context implies some information must be avaialable at some context and not on others. The second `can_see` verifies in the `edit` context. So if in the request, the user fetches with this particular context, we account for that we pull a few more informations.

This is how I noticed being used in core and how I tried to applied here. But one can argue that different forms of verifications can be chosen.

**Comment by renatonascalves** [comment]
@boonebgorges I got the question you are looking for: https://make.xwp.co/2017/07/25/defining-context-in-the-wp-rest-api/

**Comment by boonebgorges** [comment]
Thanks for the link! It definitely helps to clarify the purpose of the 'context' param. 

But I'm afraid I still don't see the connection with `can_see()` and the permission check. The permission check is intended to return a `WP_Error` in order to trigger a 403 in cases where the user is to do something they aren't allowed to do. This is an all-or-nothing response to a request: if you request (say) a group that you don't have access to view, then you get a 403 - not a partial representation of a group.

On the other hand, the relationship between 'context' and fields is more fine-grained. Say a field is specified as being valid for the 'edit' context but not 'view'. If you request a field with context=edit, you get the field. If you request it with context=view, you don't. Either way, you get a 200 response. The REST API infrastructure does the work of deciding which fields should be included with the response, based on 'context'. By that point in the process, the permission check has already been processed.

I guess the idea behind calling `can_see()` for the 'edit' context in the permission callback is that there may be fields attached to an object that (a) are only for the 'edit' context, and (b) are not visible to all users who otherwise have access to the object. When those users request the object, you don't want to give them the off-limits fields. But it seems to me that, in this case, you would simply hide the fields in the response rather than returning a 403, because presumably the user does in fact have the right to view the object.

I admit that this still may be coming from my own limited understanding of the use cases, so feel free to override my feedback :-D

**Comment by renatonascalves** [comment]
Let me think this through!!!

**Comment by renatonascalves** [comment]
@boonebgorges After much consideration, I now see what you mean and it seems correct. There is no need for the verification where we are already only adding the fields for the `edit` context.

I'm adding a patch to remove it. Thanks for pointing that out. :)
