### ISSUE TITLE
Group slug sanitization should not hit database

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#110]
This line https://github.com/buddypress/BP-REST/blame/master/includes/bp-groups/classes/class-bp-rest-groups-endpoint.php#L847 means that the `sanitization_callback` for group slugs not only checks to see that it's syntactically valid (no illegal characters, etc) but also that it's unique. This means an extra database hit, and it also means that it'll return false (or the wrong group slug) when sanitizing the value for an existing group - say, when you're trying to GET a group based on slug.

It's a shortcoming in BP that we don't have separate functions for checking that a string is a valid slug and for checking that a string is a *unique* or *non-forbidden* slug. We should probably improve that in BP. But for the purposes of the API, we can probably swap this with `sanitize_title`. See https://buddypress.trac.wordpress.org/browser/tags/4.1.0/src/bp-groups/bp-groups-functions.php?marks=442#L438

@renatonascalves Does this sound correct to you?

**Comment by renatonascalves** [comment]
I see! That might a problem! I'll update as suggested for now and save the "problem" for a patch at BuddyPress in the future.
