### ISSUE TITLE
display all activities inside a group

### ISSUE THREAD

**Issue by megin1989** [buddypress/BP-REST#112]
Thank you for providing 'BP-REST' Plugin. I have some issues. Please guide me.

1) I want to display all activities inside a group. How to display that?
	Eg: my group id is 1
		use api:- /buddypress/v1/groups/1
		Expected result:- show all activities under this group.
		
2)/buddypress/v1/messages will shows the message like "rest_authorization_required". How can i authenticate that?
  error display:- {"code":"rest_authorization_required","message":"Sorry, you are not allowed to see the messages.","data":{"status":401}}
  
3) /buddypress/v1/members - will show 9 members details. I want to show all members details.

Please help me to solve my issues.

**Comment by renatonascalves** [comment]
@megin1989 Take a look at the arguments when fetching on the `wp-json/buddypress/v1/activity`. You pass a group id and fetch activities from that particular group.

About question 2. Probably the user trying to see the messages doesn't have permission to do.

About question 3. You mean it is showing only 9 members, or it is only showing the details of 9 members but not from all of them?

**Comment by renatonascalves** [comment]
Closing this as there is no relevant bug here, only support!
