### ISSUE TITLE
Group members endpoint

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#113]
Looks like there's currently no way to handle group membership CRUD through the API.

My thought is that it probably makes sense to have this before a BP merge, at least if we plan to merge the other group-related endpoints. It feels to me like most use cases of the API (say, building a front-end interface) would need group membership functionality - at the very least, read-only to make the groups component useful.

**Comment by renatonascalves** [comment]
Agree! Let's build it next month! :)

**Comment by renatonascalves** [comment]
@boonebgorges I'm starting the development of this endpoint. I'd like to know if you have any objection of using only two endpoints.

`buddypress/v1/groups/members` for listing the members of a certain group.

And

`buddypress/v1/groups/members/member_id` for `add, remove, promote, demote, ban` the member of a specific group.
