### ISSUE TITLE
Member profile data should not be limited to 'edit' context

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#115]
Introduced in https://github.com/buddypress/BP-REST/commit/f23f9a175f655741b5ba01365727868b1219e223

Currently, xprofile data is only available in the 'edit' context:

https://github.com/buddypress/BP-REST/blame/c6bde65f5e7284b98853414be132e56c62519d1e/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L259

https://github.com/buddypress/BP-REST/blame/c6bde65f5e7284b98853414be132e56c62519d1e/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L416

This seems semantically wrong; generating a directory or a profile page in a client app is not an 'edit' operation. It also means that non-authenticated queries can't see xprofile data, which also feels incorrect to me. IMO this information should be allowed in the 'view' context (with proper controls on field visibility, of course).

@renatonascalves Does this seem correct to you as well? cc @r-a-y

**Comment by renatonascalves** [comment]
@boonebgorges It does! Added ^ implementation pending only more feedback about the field visibility part.

**Comment by renatonascalves** [comment]
I'm closing this one as the main objective of the issue was done. 💯
