### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by megin1989** [buddypress/BP-REST#119]
When i use the API "/buddypress/v1/members/1743", i got the error.
" {"code":"rest_user_cannot_view","message":"Sorry, you are not allowed to list users.","data":{"status":401}} ". 
How can i solve the issue?. Please help me. 
*I am using nginx server.

**Comment by renatonascalves** [comment]
This is a valid bug. It is related to how we are extending the class. Fix coming! :)

**Comment by renatonascalves** [comment]
@megin1989 Thanks for reporting that! =)

**Comment by megin1989** [comment]
@renatonascalves thanks for your quick reply. Its working fine now.
Also one question related to get members data.
I have some additional table columns in the user table and its extended table(custom table). Is there any hook provided to get additional table columns?

**Comment by renatonascalves** [comment]
@megin1989 We are extending WordPress core member's endpoint. It provides a filter to add more fields in the response. See here: https://core.trac.wordpress.org/browser/tags/5.0/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L948

**Comment by renatonascalves** [comment]
@megin1989 Sorry, actually, it is better that you filter this here. https://github.com/buddypress/BP-REST/blob/ec27ca1754ab37feac30d29fe26a189f25beab0f/includes/bp-members/classes/class-bp-rest-members-endpoint.php#L209
