### ISSUE TITLE
BP prefix for action/filter names

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#121]
Currently, filters and actions use the core naming convention of `rest_`, which is generally followed by the BP component name (eg `rest_xprofile_`). While I like the idea of keeping close to the BP convention, I think we should probably use some sort of BP-specific prefix. `bp_rest_` is the easiest, though it departs from WP core a bit. `rest_bp_` is another possibility. @renatonascalves What do you think?

**Comment by boonebgorges** [comment]
Maybe the same question for `WP_Error` codes.

**Comment by renatonascalves** [comment]
@boonebgorges I like `bp_rest`.

**Comment by boonebgorges** [comment]
Awesome. I'll make the change.

**Comment by renatonascalves** [comment]
@boonebgorges You changed the `rest_user_query` filter. That will break the filter we are doing with `bp_remove_has_published_posts_from_wp_api_user_query`.

**Comment by renatonascalves** [comment]
Unit tests are also not working because of the change.

**Comment by boonebgorges** [comment]
Whoops, sorry :-D
