### ISSUE TITLE
Update user xprofile data endpoint

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#122]
It looks like there's no way to update a user's xprofile data at the moment. Is that right, or am I just missing it? We should have it :) The question is whether it would be part of the `/members/` endpoint, or whether it should be part of `/xprofile/`.

**Comment by renatonascalves** [comment]
@boonebgorges I have a `XProfile_Data` endpoint branch locally that I started working last year but never finished. It was meant for updating a user's xprofile data. 

It lies in the `xprofile/data` endpoint. I don't have strong opinion of whether it should be added in the `members` or `xprofile` path.

Whatever is easier for the users. I'll see what's pending and push as a PR.

**Comment by boonebgorges** [comment]
Awesome, thanks.

As for `xprofile` vs `members`, I could see the argument either way. On the one hand, if you're updating user data, you'd first look to `members`. On the other hand, `members` is not very granular, and we'd have to have some sort of special syntax (like a multi-dimensional array sent to `xprofile_data` or something), instead of a more straightforward syntax for `xprofile`. I'd say, go ahead with whatever's easiest given your local branch, and maybe we can play with it :)
