### ISSUE TITLE
`/xprofile/fields` and `xprofile/groups` should be public

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#123]
On the current implementation, the `can_see()` check in the xprofile `fields` and `groups` endpoints prevent anyone from `bp_moderate` users from seeing the fields. I believe this should be changed. It ought to be possible to gather info about fields and groups, in order to build interfaces for displaying and editing profiles. As we don't have the concept of private groups or fields in BP, we can probably just return true in the `get` permission checks here (perhaps running through a filter). Does that seem right to you, @renatonascalves ?

**Comment by renatonascalves** [comment]
@boonebgorges I'll try to remember why I added the `can_see`. But it seems reasonable.

**Comment by renatonascalves** [comment]
Fixed introduced here: https://github.com/buddypress/BP-REST/commit/98894a15d5179be851d4ed3862faa6d4aa56de3e and here https://github.com/buddypress/BP-REST/commit/906e960f25b7cebe0bca515a7bbf5a1ba98e49de

**Comment by boonebgorges** [comment]
These changes got rolled back in https://github.com/buddypress/BP-REST/commit/c79c95290e1d3a0f7488030b5f578a68e421a796 - @renatonascalves Was the the result of a botched merge, or was there some principled reason for it? Perhaps we ought to have tests that demonstrate that these items are publicly readable.

**Comment by renatonascalves** [comment]
@boonebgorges no idea what happened. As you can see from previous commits, I had added this update, but somehow it came back. :/

**Comment by boonebgorges** [comment]
Ha ha. Merging ftw :-D
