### ISSUE TITLE
Group permissions issue vs. Missing group_id

### ISSUE THREAD

**Issue by shanebp** [buddypress/BP-REST#129]
Just started playing with this plugin - very cool... 

In `class-bp-rest-groups-endpoint.php`
`function can_see`  seems to assume that a group was found
But if a group is false because the passed group_id is _invalid_ OR _missing_, the response looks like a permission issue:  "Sorry, you cannot view the group"

Perhaps some indication in the response that `function get_group_object ` returned false? 
Or a different response ?

**Comment by renatonascalves** [comment]
@shanebp Thanks for catching that! Added an error when the group doesn't exist. :)
