### ISSUE TITLE
Group > members - can_see called twice ? 

### ISSUE THREAD

**Issue by shanebp** [buddypress/BP-REST#130]
Just curious... 

In `class-bp-rest-groups-endpoint.php`
Why is `function can_see` called twice when requesting group members? 
Add` var_dump( $request );` to the function and the same `object(WP_REST_Request) `is dumped twice. 

Perhaps this is trivial re performance... just wondering.

**Comment by renatonascalves** [comment]
@shanebp Do notice that it was updated via #129..

**Comment by shanebp** [comment]
It may not be a problem... 

Add the dump as I've shown.  
Then make a valid request.
Note that the same `object(WP_REST_Request)` is dumped twice. 
Why twice?  Why not just once ? 
 afaik - this is not related to #129

**Comment by boonebgorges** [comment]
I believe that all permission checks are called twice during REST API requests. Maybe once for OPTIONS and once for the actual method? I forget.

**Comment by shanebp** [comment]
Yeah - figured it might be something like that... just curious.  
Close this unless it has value.

**Comment by renatonascalves** [comment]
I see what you mean. I have no idea! I'd have to investigate. 

I'll close it but I'll come back here to add feedback if I find any reason for that.

**Comment by renatonascalves** [comment]
@shanebp and @boonebgorges It does indeed fire twice. Here is the reason: https://wordpress.slack.com/archives/C02RQC26G/p1548525802414800

**Comment by shanebp** [comment]
Thx for the info and link. 

> It’ll call the permission checks for the same method **as well as all the other methods registered with the same call**

Something to keep in mind!
