### ISSUE TITLE
is_user_logged_in() is always false

### ISSUE THREAD

**Issue by shanebp** [buddypress/BP-REST#131]
Sorry if I've jumping the gun here...

`is_user_logged_in()`  is being used for some permission checks, but always returns **false** so permission is denied. 

For example:
in `\includes\bp-xprofile\classes\class-bp-rest-xprofile-fields-endpoint.php` 
in `get_items_permissions_check( $request )`  permission is denied. 

Yet adding this snip to that function will return the correct logged-in user_id. 
`echo 'user_id: ';  var_dump( bp_loggedin_user_id() );`

`is_user_logged_in()` is used ~25 times throughout the plugin, so why has this not shown up before ? 

Or is it just me?  Testing on a VVV install, everything up to date.

**Comment by boonebgorges** [comment]
How are you testing the endpoints? cURL from the command line? Through JS?

**Comment by renatonascalves** [comment]
> why has this not shown up before 

I always tested via unit tests and sometimes using Postman, never in the browser. So this "bug" is a surprise to me.

I'll try to investigate. :)

**Comment by renatonascalves** [comment]
@shanebp I was able to confirm this is not a "bug" only with BuddyPress.

Try to run this into the browser and you'll get: `https://t.test/wp-json/wp/v2/themes?status=active`

`{"code":"rest_user_cannot_view","message":"Sem permiss\u00e3o para visualizar temas.","data":{"status":401}}`

Do notice that I removed the `edit_posts` check from the item permission.

It seems this is the default behavior on a browser.

**Comment by renatonascalves** [comment]
Oddly enough, `bp_loggedin_user_id()` returns the actual logged in member but `is_user_logged_in()` can't find it and returns `null`. :/

**Comment by renatonascalves** [comment]
@shanebp and @boonebgorges 

Ok! The assumption that just because one is logged in, that doesn't mean you can see the information in the REST API.

More information [here](https://wordpress.slack.com/archives/C02RQC26G/p1548547228419400) and [here](https://wordpress.slack.com/archives/C02RQC26G/p1548547426421400).

**Comment by shanebp** [comment]
Please reopen this issue. 

The point is that sometimes you allow requests without checking for  `is_user_logged_in()` , for example: `/activity`

And sometimes you do not, for example: `/xprofile/fields`

So permissions are granted in a manner that is inconsistent through-out the plugin. 

Since some permissions are granted based on the return of BuddyPress functions, I suggest that it makes sense to be consistent and to replace all instances of

`if ( ! is_user_logged_in() ) {`

with 

`if ( ! bp_loggedin_user_id() ) {`

**Comment by renatonascalves** [comment]
@shanebp The places where there is no check done for the user logged in were on purpose, such as in the activity endpoint. :)

**Comment by renatonascalves** [comment]
@shanebp As far as memory goes, the activity endpoint is the only component where it is public by default. As far as I remember, it was to mirror the desktop behavior.

So this "inconsistency" is not that well-founded.

**Comment by boonebgorges** [comment]
>  As far as memory goes, the activity endpoint is the only component where it is public by default. As far as I remember, it was to mirror the desktop behavior.

You're correct that we should be mirroring desktop behavior. But this means that most content should be readable by non-authenticated users. The exceptions are:
- non-public xprofile data
- non-public groups

Looking briefly through the plugin, I think we have it mostly correct (though I see that some xprofile changes were improperly rolled back recently - I'll reopen #123 for this).

@shanebp In this sense, I don't think we're "inconsistent" about how we check permissions. Some things are public and don't require authentication, while other things are not public and require you to be logged in. This is consistent with the rest of BP.

As for the original problem described in this ticket - that `is_user_logged_in()` returns false when accessing from a browser and not passing the `bp_rest` param - this is a design choice for the WP REST API and is not something we need to address here in the plugin.
