### ISSUE TITLE
updating user profiles via api 

### ISSUE THREAD

**Issue by dsgolfside** [buddypress/BP-REST#137]
hi guys does the buddypress api you are working on here ....is there a way to allow for creating/editing / updating a users profile data including profile photo?

**Comment by renatonascalves** [comment]
@dsgolfside You can update XProfile data, but at the top of my head, I'm not sure how one can update XProfile photo.

This is the endpoint to update XProfile information from a user:

`http://site.com/wp-json/buddypress/v1/xprofile/<field_id>/data/<user_id>`

**Comment by dsgolfside** [comment]
Thank you so much for the reply!   This gives me hope I will pass on response to the actual programmer

Is there any plans here to make it possible to use the API to add or update a profile photo?

**Comment by renatonascalves** [comment]
I'll try to keep this issue in mind and post here after I confirm this feature is in the project. Apart from that, keep an eye on the project and its updates. =)

**Comment by dsgolfside** [comment]
Hi Renato i just got a nice surprise on this issue i believe... i just read that the very guys i'm trying to work with to implement profile editing via bp-rest api reached out to you  ... app presser is the company i'm using their software  ....so this is great news... its such a big deal to my users being able to edit their profiles / upload their images

**Comment by renatonascalves** [comment]
@dsgolfside Yes! The profile upload part is almost ready here as well #161 Soon it will land here.

**Comment by dsgolfside** [comment]
Great news ! and I won’t need to forward your messages to them now

**Comment by dsgolfside** [comment]
Renato I just read the thread you mention here 161 and saw Boone on there which is awesome 

I’m planning on releasing as soon as you have the profiles working on app presser ….from where you are now about how long you think it will be till the profile can be edited / created and avatar uploaded / changed?

Thanks!

**Comment by renatonascalves** [comment]
@dsgolfside This is up to the AppPresser folks! The implementation is in place, pending their front-end team to complete it, I guess. I think you should ping them there. :)
