### ISSUE TITLE
Group Membership - Batch promote/demote/ban

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#139]
As suggested here: https://buddypress.trac.wordpress.org/ticket/8045

There might be high interest to batch promote/demote/ban/unban from the endpoint. Let's see how complex or feasible that would be.

**Comment by imath** [comment]
I agree about closing this ticket, the batch can be done from JavaScript ;)

**Comment by renatonascalves** [comment]
Cool! :)
