### ISSUE TITLE
The BP Members endpoint needs to use BP_User_Query

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#145]
After looking deeper into it, I really think we shouldn't use the `WP_REST_Users_Controller->get_items()` method as it seems very weird to me to merge the BP REST API without support to:

- BuddyPress orders (Active, Alphabetical...)
- BuddyPress member types filtering
- xProfile data search
- etc..

There should be 
- a `BP_REST_Members_Endpoint->get_items()` where the `BP_User_Query` is used,
- a `BP_REST_Members_Endpoint->get_collection_params()` to describe and validate the request parameters.

imho it's a blocker for merge.

**Comment by renatonascalves** [comment]
Seems like a valid request and thinking long-term, the right way to deal with it. I'll put a PR together in the coming week.
