### ISSUE TITLE
Blogs Endpoints

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#152]
This is a component I never used at BuddyPress, but it seems it could use some endpoints. Here are a few I noticed:

- `get_items` - Retrieve a set of blogs.

**Comment by hinnerkweiler** [comment]
I am currently getting my head around this for a project I have and it seems to me better at home in the WP-Multisite API since none of this is BuddyPress specific. 

e.g. `get_items` is already available by the MU function `get_blogs_of_user()` that lists all sites in a MU that a userid is associated with.

**Comment by renatonascalves** [comment]
You are probably right @hinnerkweiler Like I mentioned, I never used this component before with BuddyPress so I'm not 100% sure how the Blogs component is used and if it might benefit from an endpoint.

We might probably come to the conclusion that's not necessary. I'll take a deeper look soon! :)

**Comment by boonebgorges** [comment]
The BuddyPress blogs component was built specifically to make it easy to show the blogs "belonging to" a given member - the blogs on which the user has a role. WP has some core functionality for this, such as `get_blogs_of_user()`, but it performs slowly (and was even worse back in the days of WordPress MU, when BP was originally written). So I think there's some benefit at least to having the `get` methods in BP. BP itself doesn't really create blogs directly - it hooks into WP's default blog creation - so we probably don't need the create and delete methods.

It would be good to sketch use cases before going to the trouble of writing the endpoints.

**Comment by boonebgorges** [comment]
This seems fair to me. Thanks!

**Comment by imath** [comment]
I disagree 😆 ! Where are the MU endpoints you're talking about @renatonascalves ?
There are not in WP 5.3, and even if they were we support back to WordPress 4.7... I'd like to give it a closer look, because I think it's a good way to start testing using the BP REST API in directory loops.

**Comment by renatonascalves** [comment]
They don't exist yet but soon they will. And it is most liklely people will use theirs instead of the BuddyPress one.

I'm against it mainly because I don't think it is BuddyPress job to have this endpoint.

**Comment by imath** [comment]
The ticket was opened 3 years ago and hasn't evolved for more than a year :
https://core.trac.wordpress.org/ticket/40365 WordPress never listed sites of the network on the front end.

We always listed the Sites of a Network on the front end to allow their discovery. We've said we would finish endpoints for all of our components. The blogs component is one of the BuddyPress component.

I respect your opinion but I think you're wrong.

**Comment by renatonascalves** [comment]
If you feel strongly about it, I'd say let's add it.

Boone suggested adding only the `get_items` endpoint.

Do you envision more endpoints?

**Comment by imath** [comment]
I totally agree about only adding the `get_items` endpoint. 👍
