### ISSUE TITLE
Avatar Upload Endpoint

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#154]
This issue is to keep track of adding support to add avatar upload.

- `create_item` - Add image.
- `delete_item` - Delete image.
- `get_item` - Get avatar (?)

**Comment by renatonascalves** [comment]
@imath and @boonebgorges Could you weight in on where this endpoint should be?

I was thinking of something like: `buddypress/v1/members/avatar`. The same convertion would be used for the groups and blogs endpoints.

What do you guys think?

**Comment by boonebgorges** [comment]
I feel like `buddypress/v1/members/<user-id>/avatar` etc makes the most sense.
