### ISSUE TITLE
Permissions Check Override

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#158]
We should add a filter in the permission checks so that anyone can override or add their own verification before doing ours.

An interesting scenario I came across recently was validating a token. Right now the API doesn't allow to add other verifications on top of what's already there. Forcing the API user to duplicate code extending the class to override it. So a filter would facilitate that job.

My plan is to add filters with the suggested pattern:

`bp_rest_COMPONENT_NAME_API_ACTION_permissions_check`

For example, the `delete_item` endpoint of the group component would be something like:

`bp_rest_groups_delete_item_permissions_check`

**Comment by renatonascalves** [comment]
@imath and @boonebgorges Let me know if you see any possible drawbacks. :)

**Comment by boonebgorges** [comment]
Yeah, this seems OK to me.

**Comment by imath** [comment]
Same here 👌

imath
https://imathi.eu

________________________________
De : Boone Gorges <notifications@github.com>
Envoyé : vendredi, février 8, 2019 3:38 AM
À : buddypress/BP-REST
Cc : imath; Mention
Objet : Re: [buddypress/BP-REST] Permissions Check Override (#158)


Yeah, this seems OK to me.
