### ISSUE TITLE
Group Membership Request - Batch accept/reject

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#164]
As it was mentioned here: https://github.com/buddypress/BP-REST/pull/163#pullrequestreview-208965566

> Note for the future: I can see a great opportunity to allow super admins to batch reject/accept membership requests (eg: the single Group Administration screen).

**Comment by imath** [comment]
I agree about closing this ticket, the batch can be done from JavaScript ;)

**Comment by renatonascalves** [comment]
Cool! :)
