### ISSUE TITLE
Create new activity for a group is throwing error.

### ISSUE THREAD

**Issue by codetycon** [buddypress/BP-REST#176]
Hi Guys,

When I am trying to create a new activity via rest api it throwing a error. Here are my API request:

POST  `{{baseURL}}buddypress/v1/activity`

Header
```
Content-Type:application/json
Authorization:Bearer My token
```
Body 
```
{
    "content":  "New Post From API test",
    "parent": 0,
    "primary_item_id": 6,
    "secondary_item_id": 0,
    "status": "published",
    "type":"activity_update",
    "component":"activity",
    "favorited": false
        
}
```

Is threre any issue with the activity add API?

**Comment by renatonascalves** [comment]
I think you are missing the `wp-json` before the `buddypress` part???

**Comment by renatonascalves** [comment]
Ops! Sorry, it seems correct! When creating an activity, it returns the created activity object with its information.

**Comment by codetycon** [comment]
I am using wp-json in URL.

Is the issue resolved?
Is there any issue with request payload?

**Comment by renatonascalves** [comment]
Nope! Didn't see anything wrong with the payload above. :)

**Comment by codetycon** [comment]
Then why it is not working following error
```
{
    "code": "bp_rest_user_cannot_create_activity",
    "message": "Cannot create new activity.",
    "data": {
        "status": 500
    }
}
```
![image](https://user-images.githubusercontent.com/32788804/55347008-69b6da80-54d1-11e9-84b0-f21591e6ca3a.png)

**Comment by renatonascalves** [comment]
Sorry, I don't understand what you are doing there... I can confirm locally and via the code unit tests that's working correctly. I would need more information about exactly what problem are you facing.

**Comment by codetycon** [comment]
I figured out the issue now, I was passing wrong value for component, for new post in a Group component value should be "groups", here is a working sample
```
{
	
	"content":  "New Post From API Music",
    "parent": 0,
    "primary_item_id": 1,
    "secondary_item_id": 0,
    "status": "published",
    "type":"activity_update",
    "component":"groups",
    "favorited": false
}
```
