### ISSUE TITLE
email address exposed to all members

### ISSUE THREAD

**Issue by IAmTheWebb** [buddypress/BP-REST#180]
Hi,

I've just been having a look at the fantastic development that has gone in to this so far.  I noticed that the email address is returned with the member information when using buddypress/v1/groups/?/members and buddypress/v1/members 

Should this really be exposed here?  I'm guessing even with authentication enabled this information will be exposed to anyone who has a login that can query the wp-json.

Thanks

**Comment by boonebgorges** [comment]
Thanks for the feedback @IAmTheWebb ! I agree that this info should not be exposed. I assume that `/wp/users` does not expose it, right?

**Comment by renatonascalves** [comment]
@boonebgorges This is the default behavior for `BP_User_Query`. It brings the email with the query, but we can certainly change that.

I'm just not sure if that should be a site owner responsibility or the API

**Comment by renatonascalves** [comment]
Confirmed the `wp-json/wp/v2/users` doesn't show emails publicly.

**Comment by imath** [comment]
Then, we shouldn't expose it :)

**Comment by boonebgorges** [comment]
Yup, agreed. Should just be a matter of removing it from the query results before returning (and removing from the schema).

**Comment by renatonascalves** [comment]
K! Will do that!
