### ISSUE TITLE
$retval response not returned

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#182]
Shouldn't the below function return at least by default the existing $retval value.

I can not use the API unless I add a filter for every `some_action_permissions_check()` that exists and returning its own value.

Is this right or am I missing something?

```
/**
 * Checks if a given request has access to create an activity.
 *
 * @since 0.1.0
 *
 * @param WP_REST_Request $request Full details about the request.
 * @return bool|WP_Error
 */
public function create_item_permissions_check( $request ) {
    $retval = true;
    if ( ! is_user_logged_in() ) {
        $retval = new WP_Error(
            'bp_rest_authorization_required',
            __( 'Sorry, you are not allowed to create activities.', 'buddypress' ),
            array(
                'status' => rest_authorization_required_code(),
            )
        );
    }
    $item_id   = $request['primary_item_id'];
    $component = $request['component'];
    if ( true === $retval && bp_is_active( 'groups' ) && buddypress()->groups->id === $component && ! is_null( $item_id ) ) {
        if ( ! $this->show_hidden( $component, $item_id ) ) {
            $retval = new WP_Error(
                'bp_rest_authorization_required',
                __( 'Sorry, you are not allowed to create activities.', 'buddypress' ),
                array(
                    'status' => rest_authorization_required_code(),
                )
            );
        }
    }
    /**
     * Filter the activity `create_item` permissions check.
     *
     * @since 0.1.0
     *
     * @param bool|WP_Error   $retval  Returned value.
     * @param WP_REST_Request $request The request sent to the API.
     */
    return apply_filters( 'bp_rest_activity_create_item_permissions_check', $retval, $request );
}
```

**Comment by marioshtika** [comment]
Shouldn't be there something like this
```
if ( is_wp_error( $retval ) ) {
    return $retval;
}

/**
 * Filter the activity `create_item` permissions check.
 *
 * @since 0.1.0
 *
 * @param bool|WP_Error   $retval  Returned value.
 * @param WP_REST_Request $request The request sent to the API.
 */
return apply_filters( 'bp_rest_activity_create_item_permissions_check', $retval, $request );
```

**Comment by renatonascalves** [comment]
@marioshtika It does return `true` if the person has the permission and a `WP_Error` object if not.

**Comment by marioshtika** [comment]
Thank you @renatonascalves. 
You are right. I added a filter to `bp_rest_activity_create_item_permissions_check` and I was returning true by mistake and I overwrite the permission check that you created.
Which made me think. 
Should the user (or maybe some malicious plugin) overwrite the default/required permissions check?
Isn't this a security problem?
Just some thoughts for brainstorming :)

**Comment by renatonascalves** [comment]
@marioshtika I agree one can make this argument. but if that's the case, and you know a certain plugin is showing info that should not be showing, I would think a developer would find a way to mitigage that.

* Removing the bad plugin hook
* Adding a hook at a later time
* etc.

I don't see that as a security problem.  The permission hooks allows for more flexibility, including for third party plugins.
