### ISSUE TITLE
Updating activity is returning an error if parameter "type" is missing

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#184]
I am using this call `{{url}}/wp-json/buddypress/v1/activity/637?user_id=1&content=updated content`

If I enter the type (ex. type=activity_update) it works fine, but if I remove "type" it shows me the below error message
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Error::add(), 1 passed in path_to_root/wp-content/plugins/buddypress/bp-activity/classes/class-bp-activity-activity.php on line 273 and at least 2 expected in path_to_root/wp-includes/class-wp-error.php:187 Stack trace: #0 
path_to_root/wp-content/plugins/buddypress/bp-activity/classes/class-bp-activity-activity.php(273): WP_Error->add('bp_activity_mis...') #1 
path_to_root/wp-content/plugins/buddypress/bp-activity/bp-activity-functions.php(1900): BP_Activity_Activity->save() #2 path_to_root/wp-content/plugins/bp-rest/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php(487): bp_activity_add(Object(stdClass)) #3 
path_to_root/wp-includes/rest-api/class-wp-r in path_to_root/wp-includes/class-wp-error.php on line 187
```

Is that a bug? Or am I doing something wrong?

**Comment by renatonascalves** [comment]
Is this a `POST` request? Are you trying to create an activity?

Might be a bug as it requires an activity type. We are sending a default value but it appears it is not respecting it.

**Comment by marioshtika** [comment]
Yes it is a `POST` request. I am trying to **update** an existing activity (without type).

It works fine when trying to **create** an activity (without type).

**Comment by renatonascalves** [comment]
@marioshtika Thanks for bringing that to my attention. BuddyPress requires a activity type to update an activity. We were not enforcing this, so one could update without a type and get the error you mentioned.

Now activity is required to update via the REST API as well. :)

**Comment by marioshtika** [comment]
Thank you @renatonascalves. That is good news.
