### ISSUE TITLE
If Buddypress plugin does not exists it shows an error

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#185]
If the Buddypress is not activated it shows the bellow PHP error message as shown below
```
Fatal error: Uncaught Error: Call to undefined function bp_rest_namespace() in 
path_to_root/wp-content/plugins/bp-rest/includes/bp-components/classes/class-bp-rest-components-endpoint.php:24 Stack trace: #0 
path_to_root/wp-content/plugins/bp-rest/bp-rest.php(56): BP_REST_Components_Endpoint->__construct() #1 
path_to_root/wp-includes/class-wp-hook.php(286): {closure}(Object(WP_REST_Server)) #2 
path_to_root/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 
path_to_root/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 
path_to_root/wp-includes/rest-api.php(475): do_action('rest_api_init', Object(WP_REST_Server)) #5 
path_to_root/wp-includes/rest-api.php(302): rest in 
path_to_root/wp-content/plugins/bp-rest/includes/bp-components/classes/class-bp-rest-components-endpoint.php on line 24
```

Can this plugin check if the Buddypress plugin is active and show a corresponding message?
Thank you in advance.

**Comment by imath** [comment]
Nice catch @marioshtika thanks a lot!

@renatonascalves I suggest to stop hooking to `rest_api_init` but to hook to `bp_rest_api_init` it’s available since BuddyPress 2.6 see https://buddypress.trac.wordpress.org/browser/trunk/src/bp-core/bp-core-dependency.php#L260

Moreover, to leave us all options: use a function name so that we can eventually unhook it from BuddyPress eg:

```php
function bp_rest() { /* controllers registration code */ }
add_action( 'bp_rest_api_init', 'bp_rest', 5 );
```

**Comment by imath** [comment]
I think it’s more a bug than an enhancement actually 😊

**Comment by marioshtika** [comment]
Nice. Thank you.

Now it shows 
```
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
    }
}
```

Now a good enhancement would be if the message says that the reason why the request method was not found is because the BuddyPress plugin is not active.

But I am glad that this is fixed because it would break all request to the API not just for BuddyPress.

Thank you again. Keep the good work :)

**Comment by renatonascalves** [comment]
This is a default error message from WordPress.
