### ISSUE TITLE
Cache issue with the Message endpoints ?

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#190]
I've tried to implement additional fields for this endpoint, but I think, we need to rethink a bit how it has been implemented as Message meta are about a Message object not a Thread object. 

See what I had to do in BP_REST_Messages_Endpoint::prepare_item_for_response() to get successful unit tests.

> https://gist.github.com/imath/36e294e7c9e848b408a883b7252e6976

**Comment by renatonascalves** [comment]
Agree this component endpoint could be improved heavily. I basically adapted from the WP-CLI messages command: https://github.com/buddypress/wp-cli-buddypress/blob/c312f6a513ab15f4dff5d7563f7c5a703b1def43/components/message.php#L250

I just wanna somethiing there and I got there. I do however know of a company using the current Messages implementation and I think with good success.

**Comment by imath** [comment]
Nice about the company success. I'll see what I can suggest to improve it for our needs. Thanks a lot for your feedback.
