### ISSUE TITLE
Additional fields for xProfile endpoints

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#191]
Following point 3. of #189 and as we can get xprofile meta for data, field and group, I suggest to add a fourth argument to `bp_rest_register_field( $component_id, $attribute, $args = array() )` eg: `bp_rest_register_field( $component_id, $attribute, $args = array(), $type = '' )` and to use `bp_xprofile_$type` (where type would be group, field, and data) as the field key and title property of the item schema.

**Comment by renatonascalves** [comment]
Seems like a good approach to me!

**Comment by imath** [comment]
Great! I'll add a PR soon, now #189 has been merged 👍
