### ISSUE TITLE
Unit tests: more than 13000 assertions ?

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#192]
I’ve noticed there were a lot of assertions, is there a way to limit to the ones included in the test being run ?

**Comment by renatonascalves** [comment]
@imath You can test via groups.

There are component specific groups: `@group activity`
And endpoints specific groups: `@group get_items`, `@group delete_item`

The reason for the high number is because every single rest test is checking all the fields in the response: https://github.com/buddypress/BP-REST/blob/d9d64f04f2517c02831b6b989dc6b281281e6f20/tests/activity/test-controller.php#L810

This was a good way to see if in some scenarios some information would be missing or altered in some way, but maybe this could be improved.

**Comment by imath** [comment]
Thanks for your explanations 👌 I think it can stay this way for now. But we will probably need to talk about it again when BP REST API Unit Tests will be merged into BuddyPress core.

**Comment by renatonascalves** [comment]
Deal!

**Comment by dcavins** [comment]
> The reason for the high number is because every single rest test is checking all the fields in the response

Could we instead just create a format test for each type of response, and check the fields in the response in that single test? Then in other logic tests, check only that the logic has succeeded?

**Comment by boonebgorges** [comment]
I'm not sure I understand the problem with having so many assertions. Is it that the tests take a long time to run? The whole point of having automated tests is to provide coverage for things that are boring and time-consuming to test manually :) As @renatonascalves notes, there are ways to exclude time-consuming tests when doing active development on unrelated features.

**Comment by dcavins** [comment]
I don't think there's necessarily a problem, but the tests as written are a little broad in what they are checking. For instance, in `BP_Test_REST_Group_Membership_Request_Endpoint`, `get_items()` checks that the returned values match the format, but so do the tests for `update`, `delete` and so on, when they could just be checking that the update or delete occurred.

**Comment by boonebgorges** [comment]
Ah yes, that seems right. The tests should definitely be targeted :)

**Comment by dcavins** [comment]
But let me be the most recent to give appreciation for all the work @renatonascalves has done providing thorough test coverage. It's fantastic for me to be able to go to work on the invitations stuff and run a complete suite of tests to ensure that I'm not breaking the world (which I was). Thanks Renato!

**Comment by renatonascalves** [comment]
Thanks guys! Indeed the tests can be improved. At the time I copied the structure from WordPress core rest tests and they seemed to be doing that so I thought it was okay! :)

**Comment by imath** [comment]
Some more explanations about this feedback:
1. To compare, BuddyPress has less than 3000 assertions, that’s why I was surprised
2. It’s pretty confusing when you write a unit test with 2 assertions the result tells you more than 300 hundred was done. Now I know this it’s fine : I first run my test with no assertions to get the extra assertions count and I do a substraction once I add my assertions 👌
3. I’m not criticizing, the work accomplished is great 👍 I’m just wondering 😊

I wonder for instance if running the same assertions multiple times could be avoided once they are merged into Core.

**Comment by renatonascalves** [comment]
> I wonder for instance if running the same assertions multiple times could be avoided once they are merged into Core.

Agree! And that's the improvement that could be made and the one I'd sugest.

**Comment by imath** [comment]
Well actually, I believe this was a `WP_Test_REST_Controller_Testcase` issue. Tests are now looking good. The number of assertions went down to 3162.
