### ISSUE TITLE
Showing a warning on the avatar endpoint

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#195]
I am uploading an avatar through the endpoint `/wp-json/buddypress/v1/members/1/avatar` and the below warning is shown:
```
Warning: unlink(/path_from_root/wp-content/uploads/avatars/1/image.jpg): No such file or directory in /path_from_root/wp-content/plugins/BP-REST/includes/bp-attachments/classes/trait-attachments.php on line 102
[{"full":"https:\/\/website_url\/wp-content\/uploads\/avatars\/1\/5d31914f295a8-bpfull.jpg","thumb":"https:\/\/website_urll\/wp-content\/uploads\/avatars\/1\/5d31914f2d86c-bpthumb.jpg"}]
```
The upload is working and the response is correct I just can not retrieve it because of the warning message.

**Comment by renatonascalves** [comment]
Are you using the `file` handler or is it one with a custom key?!

**Comment by marioshtika** [comment]
Yes I am using the `file` handler.

**Comment by marioshtika** [comment]
Hello @renatonascalves, any update on this?

**Comment by imath** [comment]
What about doing a `file_exists()` check before using `unlink()` 😉

**Comment by marioshtika** [comment]
I am guessing the image is being already deleted from the code in [line 83](https://github.com/buddypress/BP-REST/blob/master/includes/bp-attachments/classes/trait-attachments.php#L83)
```
// Delete existing image if one exists.
$this->delete_existing_image();
```
Or is it something else?

**Comment by renatonascalves** [comment]
@imath Thanks! Good idea! That should fix this warning!

@marioshtika Those are different things. The method is removing already uploaded avatars. The error you mention is the image is being uploaded.

We save it temporarily before cropping it.
