### ISSUE TITLE
how to upload images in activity

### ISSUE THREAD

**Issue by sarin-citrus** [buddypress/BP-REST#208]
Using the API I am able to add activity to my group..but please let me know how can i upload (single and multiple)images to the activity

**Comment by renatonascalves** [comment]
@sarin-citrus Adding images to activity items is not baked into the API. But you can hook into `bp_rest_activity_pre_insert_value` and add the images using this hook.

About the group, can you share the endpoint and arguments you are using to post an activity to the group?
