### ISSUE TITLE
internal error 500 after install bp-rest

### ISSUE THREAD

**Issue by alejo0789** [buddypress/BP-REST#213]
Hi, i don´t know why after install and activate bp-rest i get internal error 500 it seems to be  server error o .htacces but how can I to test thanks.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

when i disable budypress plugin the error disappears

budypress 4.4.0

**Comment by renatonascalves** [comment]
@alejo0789 Do you have debug.log enabled and if you do, can you share more what you see there?

**Comment by renatonascalves** [comment]
I can't replicate this bug.
