### ISSUE TITLE
how to get recent activity and comments of a user

### ISSUE THREAD

**Issue by sarin-citrus** [buddypress/BP-REST#214]
Hi 
i am using buddypress/v1/activity endpoint to get the activity of the user...can i get the comments that user made on another activity using this endpoints..i want to show recent activity and comments of the user in my api. now i am only getting activity of the user not comments included in this response
Thank you

**Comment by renatonascalves** [comment]
@sarin-citrus There is a param `display_comments` which you can use to display the comments together with the activities.

**Comment by sarin-citrus** [comment]
@renatonascalves thanks for quick response...i used the display_comments..but what i want is to get the comment of the user on another users activity..can i get such comments also when i give 'user_id'

**Comment by renatonascalves** [comment]
@sarin-citrus You can't do that in the same request. You would need to make another request for that user and his comments.

Maybe in your app, merge both results. The API works the same as in a regular BuddyPress site.

**Comment by sarin-citrus** [comment]
@renatonascalves thank you for reply..i have one more doubt...using the above API i can get all activity of the user and the comments of the activity..is there any way to get all comments only of particular user id

**Comment by renatonascalves** [comment]
@sarin-citrus You can get activities for a specific user using the `user_id=user-id` and request that it comes with his comments `display_comments=true`.

You can't get only the comments right now.
