### ISSUE TITLE
Users cannot delete their own group membership request

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#218]
Only administrators of groups can reject memberships requests for a group, a non-member cannot cancel their own requests.

In relation to the BP_REST_Group_Membership_Request_Endpoint class:

- Description for `update_item()` states `'Accept or reject a pending group membership request.'`, in reality this endpoint can only accept requests, `delete_item()` is available for rejecting requests.
- `delete_item_permissions_check()` uses `update_item_permissions_check()` to perform the permission check
- `update_item_permissions_check()` requires a user be an admin of the group to perform the action.

On the surface it looks to me like the `update_item_permissions_check()` function needs to be duplicated into `delete_item_permissions_check()` and the permission check should allow the request if the logged in user ID is the same as the user ID in the request.

(This would also mean the error message generated when permission is denied would be more relevant.)

If the user has permission and they are deleting their own requests, `groups_delete_membership_request()` should be called instead of `groups_reject_membership_request()`.

I could put together a pull request for the changes above but I am not sure if it would be better to have a dedicated REST endpoints for deleting membership requests versus rejecting them.

**Comment by imath** [comment]
Thanks for your feedback 💪😍, we are about to merge #206 to use the new BP Invitations API (which also takes care of membership). Could you check once it’s done if it fixes this issue ?

**Comment by sjregan** [comment]
I've taken a quick look through the pull, I think there is still an issue regarding `groups_delete_membership_request()` vs `groups_reject_membership_request()` but it will be easier for us all to discuss after the merge.

**Comment by imath** [comment]
Ah yes very good point. We had this discussion during our latest BuddyPress dev-chat. Let's use this issue to work on it.

@dcavins can you have a look at it?

**Comment by dcavins** [comment]
Thanks! See https://github.com/buddypress/BP-REST/pull/221
