### ISSUE TITLE
Notifications endpoint does not return reliable content when using POST method

### ISSUE THREAD

**Issue by mukaschultze** [buddypress/BP-REST#237]
### Current behaviour

Making a POST (or any other verb to update the item) to the notifications endpoint returns the old element instead of returning the updated element. If nothing is changed it returns code 500: `bp_rest_user_cannot_update_notification`

### Expected behaviour

The endpoint should return the edited element, and, in my opinion, it shouldn't return code 500 when there are no changes.

### How to reproduce

Try the following request:
`{{site_url}}/wp-json/buddypress/v1/notifications/25?unread=1&is_new=1`

If the current `unread` value is 0 the returned element also returns 0 instead of returning the expected updated value 1.
If the current `unread` value is 1 the server throws `bp_rest_user_cannot_update_notification`

Also note that the request requires the `is_new` parameter to work, which is odd because the field name that is going to be changed is `unread`, this seems inconsistent, but I may have missed something.

**Comment by renatonascalves** [comment]
@mukaschultze You seems to be using params which are not accepted in the current version of the API.

For more info on how to update a notification: https://imath-buddydocs.pf1.wpserveur.net/bp-rest-api/reference/screen-notifications/#update-wether-a-screen-notification-is-new-or-not

**Comment by renatonascalves** [comment]
Closing this for now as I don't this is a problem with the current API but a wrongly use of the API with params that don't exist at the moment.

Do ping me again if you need my help with something. and thanks for using the API. :)
