### ISSUE TITLE
The Blogs Controller should fetch Blog avatars

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#245]
We'll need to wait for https://buddypress.trac.wordpress.org/ticket/8150 to be fixed. To fetch the blog avatar it will be required to use the `bp_get_blog_avatar()` because it's checking for the site icon to eventually replace the avatar of the Blog's admin by it.

**Comment by renatonascalves** [comment]
After that's in, I wonder if we should add a:

`http://site.com/wp-json/buddypress/v1/blogs/<blog_id>/avatar`

**Comment by imath** [comment]
I think we should add a Blog Avatar Upload feature if this is what you meant in your previous comment and build the feature in BuddyPress Core using this endpoint.
