### ISSUE TITLE
buddypress signup

### ISSUE THREAD

**Issue by hijoncon** [buddypress/BP-REST#252]
How does buddypress/v1/signup works without jwt? It's weird to store my token in app. Is there a way to works without jwt?

**Comment by renatonascalves** [comment]
The recommended way is to create a signup from an authenticated request. So you would have to authenticate with JWT or other option to create a user signup.

Another option that I **don't recommend** but that's possible is to hook into `bp_rest_signup_create_item_permissions_check` and allow public signup. But you would be opening your API, **allowing ANYONE to create a signup**.

Use at your own risk. :)
