### ISSUE TITLE
buddypress Post api not working

### ISSUE THREAD

**Issue by ankit-aresourcepool** [buddypress/BP-REST#256]
Hi

i am trying to post below request
https://www.vetswhatsnext.org/wp-json/buddypress/v1/groups/6/members/62

but i am not getting below response

{
    "code": "bp_rest_authorization_required",
    "message": "Sorry, you need to be logged in to make an update.",
    "data": {
        "status": 401
    }
}

i am also sending Bearer token in the header

http://prntscr.com/qdhqhk
![Screenshot_1](https://user-images.githubusercontent.com/37215290/71249251-b7ff5880-2342-11ea-9262-603e36a51d3a.png)

please help me how to fix it asap

thanks

**Comment by ankit-aresourcepool** [comment]
below are token request 
![Screenshot_2](https://user-images.githubusercontent.com/37215290/71249345-f5fc7c80-2342-11ea-95ff-72876932570e.png)

**Comment by renatonascalves** [comment]
Hi! In a nutshell, the `update_item_permissions_check` method is checking if the user is logged in with `is_user_logged_in()` and for your use case, it seems the user is not logged in.

I can see you are sending the token with the request, so I'd ask to investigate if the user can perform other actions with the token and only this endpoint/request is the problem.

I'd guess the user is not authenticated correctly with the token and WordPress is not recognizing the user as a logged in user. This requires more investigation.

I'm closing the issue for now as I don't think this is an issue with the BP REST API. But feel free to leave other comments here with what you find or open the issue again if you really feel something in BuddyPress is not right.

:)
