### ISSUE TITLE
Get activities only from my friends

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#258]
Hello,

I am using the `http://site.com/wp-json/buddypress/v1/activity` endpoint. But I couldn't find any reference in the documentation about getting all activities only from my friends.

Is this possible, or am I missing something?

Thank you in advance.

**Comment by imath** [comment]
Hi @marioshtika 

Thanks a lot for reporting this issue. @renatonascalves I believe we need to add a `scope` parameters to the collection schema, where this scope could be:
`type => 'string',
default => 'just-me',
enum => array( 'just-me', 'friends', 'groups', 'favorites', 'mentions' )

Once done I agree we should improve the documentation to explain how to request by scopes.

**Comment by marioshtika** [comment]
Hello @imath and thank you for the quick response.
That sounds great. 
It will be very helpful if that was possible.

**Comment by renatonascalves** [comment]
Updating from `bug` to `enhancement` as this was not implemented before instead of being broken because of the previous implementation.

:)

**Comment by renatonascalves** [comment]
@marioshtika We just merged this. Try it and let me know if that works out for you. :)
