### ISSUE TITLE
Type mismatch in the schema description of the Group Membership endpoint

### ISSUE THREAD

**Issue by ExoGeek** [buddypress/BP-REST#261]
In the file class-bp-rest-group-membership-endpoint.php, function get_item_schema() :

Description and type of properties "is_mod", "is_banned", "is_admin" and "is_confirmed" should be boolean and not integer.

See prepare_item_for_response() : 

`array(
				'is_mod'        => (bool) $group_member->is_mod,
				'is_admin'      => (bool) $group_member->is_admin,
				'is_banned'     => (bool) $group_member->is_banned,
				'is_confirmed'  => (bool) $group_member->is_confirmed,
				'date_modified' => bp_rest_prepare_date_response( $group_member->date_modified ),
			)`

**Comment by renatonascalves** [comment]
Thanks for catching that! Will add a fix. :)
