### ISSUE TITLE
Request args description when creating a friendship request

### ISSUE THREAD

**Issue by ExoGeek** [buddypress/BP-REST#263]
Just let you know that the args description is missing for CREATE friendship endpoint (file class-bp-rest-friends-endpoint.php)

`OPTIONS {{host}}/wp-json/buddypress/v1/friends`

See Args of POST method. Request Args should be : 
- initiator_id
- friend_id
- force

**Comment by renatonascalves** [comment]
Bug confirmed! Thanks for catching that.
