### ISSUE TITLE
PHP Notice Error when retrieving Activity

### ISSUE THREAD

**Issue by ExoGeek** [buddypress/BP-REST#266]
A PHP error is reported when accessing that route : 

`OPTIONS {{host}}/wp-json/buddypress/v1/activity/8`

Here is the error :

`Notice: Trying to get property 'component' of non-object in <local path>\buddypress\bp-activity\bp-activity-functions.php on line 3124`

I call that route without beeing logged in.

**Comment by renatonascalves** [comment]
Let me check!

**Comment by renatonascalves** [comment]
I couldn't replicate the error.

Which version of BuddyPress and WordPress are you using?

**Comment by ExoGeek** [comment]
You have to request an ID_Activity which doesn't exist. 

In my example, ID_Activity = 8 doesn't exist. If I request on a existing ID_Activity, I don't get error.

**Comment by renatonascalves** [comment]
I see the issue! Sorry for that, the unit tests misled me into thinking the result was right. But a non-existent activity causes a bug.
