### ISSUE TITLE
Favorited field not working on activity

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#267]
Hello, 

I am trying to mark an activity as 'favorited' as mentioned [here](https://developer.buddypress.org/bp-rest-api/reference/activity/#add-or-remove-a-specific-activity-from-favorited-activities) 
```
POST /buddypress/v1/activity/<id>/favorite
```

This is working fine, but when I retrieve the current activity with 
```
GET /buddypress/v1/activity/<id>
```
 the response in the favorite list is always false `"favorited": false,`

Am I doing something wrong or is there a 🐛 here?

**Comment by renatonascalves** [comment]
Let me check! :)

**Comment by renatonascalves** [comment]
Ok! A question @marioshtika 

* Are you doing a `GET` request logged in with the favorited activity owner?

**Comment by marioshtika** [comment]
Hello, @renatonascalves,

you are right, I was making the `GET` request without passing the logged-in user.
 
I am sorry for the trouble :)
