### ISSUE TITLE
Is there any plan of adding "Flag" an activity as inappropriate

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#268]
Hello,

just putting this here, as a feature request. 😎

Is there any plan of adding "Flag as inappropriate" to an activity?

**Comment by renatonascalves** [comment]
This is not something that BuddyPress core supports, so I'm not sure. Maybe not. This is more of flag content plugin to add support for it.

**Comment by marioshtika** [comment]
Thank you for the response. I suspected that was the case :)
