### ISSUE TITLE
Retrieve information if member is my friend

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#270]
Hello everyone

I am getting a specific member as shown in the [documentation](https://developer.buddypress.org/bp-rest-api/reference/members/#definition-3) with 
```GET /buddypress/v1/members/<id>```

Is there a way to have the information if this member is "my friend"?

Thank you in advance

**Comment by renatonascalves** [comment]
This information is not part of the response since this endpoint is to fetch a member not a friendship.

`GET /buddypress/v1/friends/friendship_id` is the correct endpoint if you want to confirm a friendship between two users.

This endpoint returns:

```
{
    "id": 1,
    "initiator_id": 1,
    "friend_id": 3,
    "is_confirmed": false|true, <- This is where you can confirm if they are friends
    "date_created": "2020-01-16T11:20:09"
}
```

Let me know if that solves your issue or how we can improve. :)

**Comment by ExoGeek** [comment]
Another solution could be to register a new field in the member enpoind response like this : 

`bp_rest_register_field(
			'members',
			'friendship_status',
			$this->get_schema_friendship_status()
		);`

`private function get_schema_friendship_status(){
		return array(
			'get_callback'  => array( $this, 'register_friendship_status' ),
			'schema'        => array(
				'description'   => __( 'Friendship relation with current logged in user.', 'pictoflash' ),
				'type'          => 'string',
				'enum'          => array('is_friend', 'not_friends', 'pending','awaiting_response'),
				'readonly'      => true,
				'context'     => array( 'embed', 'view', 'edit' ),
			),
		);
	}`

`public function register_friendship_status( $user ) {
		return friends_check_friendship_status(get_current_user_id(), $user['id']);
	}`

**Comment by marioshtika** [comment]
@renatonascalves I didn't find any documentation about the `friends` endpoint

Also I was hoping to see the **status** of the **friendship** in the `members` endpoint when the request was made from a logged in user.

The same as the `"favorited": true,` on activity, when the request was made with a logged in user.

@renatonascalves do you think this is something that can improve the `members` endpoint so that there is no need to make an extra request for each member.

Example: if I want to show a list with 100 members and I want to show my relation to these members I have to make 100 more request to have this information.

What do you think?

**Comment by renatonascalves** [comment]
@marioshtika I think it is a good idea. I added this via #274 :)
