### ISSUE TITLE
Filter to change message content

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#278]
Hello everybody,

I am trying to extend the message endpoint and more specifically the `create_item` action.

Is there a filter to change the content of the message, before it is saved in the database?

Thank you in advance?

**Comment by renatonascalves** [comment]
Good catch! Most of the BP `create_item` endpoints have a hook to change or update content before creation or update.

Currently there is any for the message `POST` request. But this is an easy win. Will introduce that shortly. Thanks for bringing that to our attention. :)

**Comment by renatonascalves** [comment]
@marioshtika We just added an update where you will be able to update an message information before it is being added in BuddyPress. :)

**Comment by marioshtika** [comment]
Hello @renatonascalves,

I tested the changes you made and the first thing I noticed is that when [replying to a thread](https://developer.buddypress.org/bp-rest-api/reference/private-messaging/#replying-to-an-existing-messages-thread) it is returning me an error.
```
{
    "code": "rest_missing_callback_param",
    "message": "Missing parameter(s): recipients",
    "data": {
        "status": 400,
        "params": [
            "recipients"
        ]
    }
}
```
it looks like after the changes the receipients are required. In the documentation, I didn't find any reference for this. I don't know if I am doing something wrong.

Also, I made a quick test to use the filter "bp_rest_messages_pre_insert_value" but I wasn't successful on my first attempt. I will make some more tests and let you know.

**Comment by renatonascalves** [comment]
Correct! The recipients were updated to be required everywhere. It was _loosely_ required before. The documentation wasn't updated yet.

Let me know how it goes with the hook tests.

cc: @imath

**Comment by marioshtika** [comment]
Hello @renatonascalves and sorry for the late response.

I  added the recipients to the request and also tested the `bp_rest_message_pre_insert_value` filter and it is working perfectly. (I had a typo on my first test)

Thank you very much
