### ISSUE TITLE
Activity endpoint - GET

### ISSUE THREAD

**Issue by paulgibbs** [buddypress/BP-REST#28]
Partially implemented in master. Both `/activities/` and `/activities/<id>/`are in.

There are a number of outstanding TODOs and considerations:
- [ ] Verify how we need to treat `show_hidden`. Currently, it assumes we only need to force it true/false depending if we're querying for Group activities or not, and if the current user is a member of that Group.
- [ ] With that, we need to handle someone requesting an activity item via its `ID` that that user shouldn't have access to. How do we know that? Some kind of post-request check, I guess. --> use logic from `bp_activity_screen_single_activity_permalink()`
- [ ] The above should also cover off general permissions / access checks, etc.

**Comment by pives** [comment]
Hey, i just found this project and i'm unclear as to where it stands. But i'd love to help out if it's possible as i have to implement some of this stuff anyway. I don't have a wordpress slack login so i can't really see the 'state' of the project anywhere. Don't want to bother anyone if I can just read something to get up to speed on the status and plans. .. 
Thanks!
Phil

**Comment by modemlooper** [comment]
Read this it explains a bit about contributing. https://bpdevel.wordpress.com/2016/01/14/bp-rest-api-dev-chat-summary-for-january-14-2016/

**Comment by paulgibbs** [comment]
For:

> With that, we need to handle someone requesting an activity item via its ID that that user shouldn't have access to.

We can re-use the logic from `bp_activity_screen_single_activity_permalink()`, probably split off into a common function so both places can use it.

**Comment by pives** [comment]
Great, Thanks for quick responses. I am recovering from and still in Phillytechweek,  then i'll be my usual responsive self on here. Thanks!

**Comment by pives** [comment]
Ok, so this thing isn't as far along as i thought. That's fine. I'm probably gonna write some  quick and dirty code and then i can clean up activities and bring it in here. I have a couple questions. Happy to get on a chat or schedule one.
Is anything working at this point? For example i have WP-JSON Endpoint working via /wp/v2"  and i don't even see the BP-REST API registered. Though i do see oauth that i installed. Any help on just .. where this thing is at. Just checking im' not missing something.   What would actually call do_action('bp_rest_api_init')?

**Comment by renatonascalves** [comment]
Closing this as it is already working on master.

Thanks, everyone! :)
