### ISSUE TITLE
Cannot remove friend via friends endpoint

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#280]
The friends endpoint allows creating friendship requests, accepting friendship requests, rejecting friendship requests, withdrawing friendship requests but it does not allow removing friends.

Performing a DELETE on `/friends/<friendship-id>` endpoint deals with friendship requests, not friendships themselves. Either `friends_withdraw_friendship()` or `friends_reject_friendship()` is called, `friends_remove_friend()` is never called within the plugin.

`friends_withdraw_friendship()` will not delete confirmed friendships.

**Comment by renatonascalves** [comment]
That's true! I don't remember why but I think there was a reason for that. 

Will confirm with the team what that was and if not, introduce one for delete actions. :)

**Comment by renatonascalves** [comment]
@imath Do you remember why that was?

**Comment by imath** [comment]
Well, what I remember is: I thought it was best to put reject/withdraw and accept into the update_item() method and use the delete_item() method to delete a friendship. Then I believe a global consensus decided reject/withdraw should go into the delete method.

Let's add it into the delete_item() method using a specific new parameter.

**Comment by renatonascalves** [comment]
@sjregan Suggestion updated! :)
