### ISSUE TITLE
Simplify BuddyPress Namespace

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#29]
The BuddyPress namespace should be simplified from buddypress/v1 into bp/v1.

This is how WordPress and WooCommece do theirs.

WordPress: wp/v2
WooCommerce: wc/v1

**Comment by paulgibbs** [comment]
I don't know about "should". The fewer letters in the endpoint name increases the risk of conflicts if other plugins choose the same... this is probably unlikely, but that's why the full-length title was chosen.

I am not particularly worried if we decide to shorten it, however.

**Comment by renatonascalves** [comment]
Definitely BuddyPress should take precedence over any plugin. But I'm gonna check how those guys, WC and WP, are checking for possible namespace conflicts...

**Comment by modemlooper** [comment]
API endpoints need to be self explanatory. Naming should be full text. This will make sure a user knows its buddypress and as Paul explained will eliminate collisions.

**Comment by renatonascalves** [comment]
I'm not sold, but I go where the consensus goes. =)

**Comment by r-a-y** [comment]
I personally prefer the shortform as well.  Regardless, whatever we choose should be filterable so devs can change it.

**Comment by modemlooper** [comment]
Actually, namespaces should be filterable. So, you should be able to change it to anything

**Comment by renatonascalves** [comment]
Making a note I'll add a filter for the namespace. :)

**Comment by rahulkhosla** [comment]
Please, could you update the docs? First time using this API and I didn't know that it was /wp-json/buddypress/v1/

**Comment by renatonascalves** [comment]
@rahulkhosla Sure! I'll add more doc and some examples.
