### ISSUE TITLE
User can create and force friendships for other pairs of users

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#291]
Currently users can create friendships that do not involve themselves, ie. user 1 can create a friendship between users 2 & 3.

[This pull request](https://github.com/buddypress/BP-REST/pull/290) solves that by forcing the initiator in the friendship to be the one making the API request.

I'm sorry but the pull request does not include updates to the unit tests.

Additionally, the pull request does not address the ability for users to force their friendship upon other users. This is a security hole as plugins and themes sometimes limit which data another user can see unless they are friends.

**Comment by renatonascalves** [comment]
@sjregan 

I created another PR on #293, introduced a change to avoid regular users to create friendship request, with unit tests. Thanks for bringing that to my attention.

:)
