### ISSUE TITLE
Is there documentation or examples?

### ISSUE THREAD

**Issue by JulioPablo** [buddypress/BP-REST#295]
Hi!

Wondering if there's documentation regarding the shape of the request objects?
How the responses would look and so on. 

Looking into using Wordpress with BBpress REST api as backend for a mobile app that needs forums.

Sorry about opening an issue to ask the question, wasn't sure how else to ask.

Best regards, 
Julio.

**Comment by renatonascalves** [comment]
@JulioPablo We have documentation with a lot of information about the request and response params.

https://developer.buddypress.org/bp-rest-api/

You mentioned bbPress, bear in mind this is a BuddyPress package not a bbPress one. :)
