### ISSUE TITLE
Update BP REST API Documentation

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#301]
This issue will help us to keep track of the updates we do about the [BP REST API Documentation](https://developer.buddypress.org/bp-rest-api/).

I've just started today updating it. The idea is to post a comment when you decide to update a particular endpoint documentation and to update it once you finished.

Here's a [way to build a tool](https://gist.github.com/imath/5f95ef11b6dd0f6852aa03c0ef30e485#file-bp-custom-php) to ease your documentation updates.

**Comment by imath** [comment]
- [x] `BP_REST_Groups_Endpoint` Updated see https://developer.buddypress.org/bp-rest-api/reference/user-groups/groups/

**Comment by imath** [comment]
- [ ] BP_REST_Members_Endpoint Updating see https://developer.buddypress.org/bp-rest-api/reference/members/

**Comment by imath** [comment]
- [ ] `BP_REST_Blogs_Endpoint` Creating see https://developer.buddypress.org/bp-rest-api/reference/blogs/

**Comment by imath** [comment]
- [ ] `BP_REST_Signup_Endpoint` Creating see https://developer.buddypress.org/bp-rest-api/reference/signup/

**Comment by imath** [comment]
- [ ] `BP_REST_Friends_Endpoint` is being created see https://developer.buddypress.org/bp-rest-api/reference/friends/

**Comment by imath** [comment]
- [x] `BP_REST_Attachments_Blog_Avatar_Endpoint` is created see https://developer.buddypress.org/bp-rest-api/reference/attachments/blog-avatar/

**Comment by imath** [comment]
- [x] `BP_REST_Attachments_Member_Cover_Endpoint` is created see https://developer.buddypress.org/bp-rest-api/reference/attachments/member-cover-image/
- [x] `BP_REST_Attachments_Member_Avatar_Endpoint` has been updated see https://developer.buddypress.org/bp-rest-api/reference/attachments/member-avatar/

**Comment by imath** [comment]
- [x] ` BP_REST_Attachments_Group_Cover_Endpoint` is created see https://developer.buddypress.org/bp-rest-api/reference/attachments/group-cover-image/

**Comment by mercime** [comment]
`BP_REST_Activities_Endpoint` has been updated see https://developer.buddypress.org/bp-rest-api/reference/activity/

**Comment by mercime** [comment]
`BP_REST_xProfile_Field_Groups_Endpoint` has been updated.  See https://developer.buddypress.org/bp-rest-api/reference/extended-profiles/profile-group/

**Comment by mercime** [comment]
BP_REST_XProfile_Fields_Endpoint has been updated. See https://developer.buddypress.org/bp-rest-api/reference/extended-profiles/profile-field/

**Comment by mercime** [comment]
BP_REST_XProfile_Data_Endpoint has been updated. See https://developer.buddypress.org/bp-rest-api/reference/extended-profiles/profile-data/

**Comment by mercime** [comment]
BP_REST_Group_Membership_Endpoint is updated. See https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-membership/

**Comment by mercime** [comment]
`BP_REST_Messages_Endpoint` is updated. See https://developer.buddypress.org/bp-rest-api/reference/private-messaging/

**Comment by mercime** [comment]
`BP_REST_Notifications_Endpoint` is updated. See https://developer.buddypress.org/bp-rest-api/reference/screen-notifications/

**Comment by mercime** [comment]
`BP_REST_Components_Endpoint` reviewed. No changes needed 😍
See https://developer.buddypress.org/bp-rest-api/reference/components/

**Comment by mercime** [comment]
`BP_REST_Attachments_Group_Avatar_Endpoint` is updated. See https://developer.buddypress.org/bp-rest-api/reference/attachments/group-avatar/

**Comment by mercime** [comment]
BP_REST_Group_Invites_Endpoint is updated. See https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-invites/

**Comment by mercime** [comment]
BP_REST_Group_Membership_Request_Endpoint reviewed. Updates done but have a couple issues to be resolved. See https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-membership-requests/

**Comment by renatonascalves** [comment]
Can we close this issue? Is it done?
