### ISSUE TITLE
Create Custom Endpoint Route?

### ISSUE THREAD

**Issue by sniffingpickles** [buddypress/BP-REST#312]
I'm a little stuck on the documentation, how would I go about creating a new route for say.... adding reactions to an activity field? 

I started playing around with building it but became confused as to how to actually execute a reaction on an activity

```
bp_rest_register_field(
        'activity',      
        'reactions', 
                array(
                    'get_callback'    => 'get_additional_field',   
                    'update_callback' => 'update_additional_field', 
                    'schema'          => array(                               
                        'description' => 'Reactions on Activity',
                        'enum'          => array('HAPPY', 'LOVES', 'DISLIKES','FUNNY', 'WOW', 'ANGRY', 'SAD'),
                        'type'        => 'string',
                        'context'     => array( 'view', 'edit' ),
                    ),
                  )
              );
```

**Comment by renatonascalves** [comment]
I'd recommend taking a look at how we are adding endpoints for inspiration to add your implementation.

**Comment by imath** [comment]
Hi @sniffingpickles 

I advise you to rename your `get_additional_field` and `update_additional_field` prefixing it, eg: `sniffingpickles_get_additional_field` and `sniffingpickles_update_additional_field`.

Then you can create the two functions:

```php
// Includes the reaction value into the Activity Meta property of items fetched by get_item(s) method.
function sniffingpickles_get_additional_field( $data, $attribute )  {
	return bp_activity_get_meta( $data['id'], $attribute );
}

// Create or updates the meta data during create_items() and update_items() methods.
function sniffingpickles_update_additional_field( $value, $data, $attribute ) {
	return bp_activity_update_meta( $data->id, $attribute, $value );
}
```

**Comment by sniffingpickles** [comment]
Hi imath, 

Thank you for your reply.  I created functions previously, however, where do I send the `POST` request?  I thought I was trying to mimic the "favorite" functionality, so I had intended to create an extended route as well; or am I just adding 'reactions' to a field in the ajax request?

Sorry for asking too many questions, the source and documentation are extremely helpful, but there's a tremendous amount of back & forth between googling what each WP function does, on top of the BuddyPress functionality.  It's all new to me.

**Comment by mercime** [comment]
Posted also at https://buddypress.org/support/topic/how-to-create-custom-endpoint-route

**Comment by renatonascalves** [comment]
I think that's the better place for the question. Sorry for not suggesting it sooner. :)

**Comment by sniffingpickles** [comment]
> I think that's a better place for the question. Sorry for not suggesting it sooner. :)

lol I asked there at the same time, and only got a link referencing to my own github post :D

**Comment by imath** [comment]
Hi @sniffingpickles you don’t need additional routes to manage your additional field. As you’ve used the function to register it, you just need to add the `reaction` key with the needed value as a request parameter just like you’d do for the one described into the `create_item` or `update_item` methods. Using the `get_item` and `get_items` method of the activity endpoint will include the `reaction` key with the value set for it into their responses.

In this example of use of the create activity endpoint: https://developer.buddypress.org/bp-rest-api/reference/activity/#example-of-use-2 your code should look like this:

```
bp.apiRequest( {
  path: 'buddypress/v1/activity',
  type: 'POST',
  data: {
    context: 'edit',
    user_id: 1,
    component: 'activity',
    type: 'activity_update',
    content: 'Hello <b>BuddyPress</b>',
    reaction: 'like'
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```
