### ISSUE TITLE
Group Membership Request Endpoint: Message parameter

### ISSUE THREAD

**Issue by mercime** [buddypress/BP-REST#313]
I noticed that the message parameter was included while reviewing the [Group Membership Request Endpoint](https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-membership-requests/). There's no UI in the current bp-nouveau/ bp-legacy template packs for the user to send a message when requesting for group membership nor is there one for the group admin to send to user who requested membership. 

![bp-rest-grp-mbrreq-sch](https://user-images.githubusercontent.com/648086/81808539-b4789380-94d4-11ea-87bf-fa8d4c85222f.png)

![bp-rest-grp-mbr-req](https://user-images.githubusercontent.com/648086/81808563-bb070b00-94d4-11ea-804a-4678fe877380.png)

Some years ago I do remember seeing a text input field show up when a user clicks on the "Join" group button of a Private Group to send a message. Can't see one now. Sorry, I can't recall right now whether it was in bp-default theme or bp-sn-parent theme or something else. 

Per @imath, "I’d remove the « message » rows because this might not be implemented into the endpoint. Once the issue will be fixed we will be able to put them back" 
Removed from `Schema` table and in the `Request a Group Membership` table at https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-membership-requests/

**Comment by imath** [comment]
Hi @mercime 

I completely misunderstood! Really sorry.

I thought the documentation page on developer.buddypress.org was mentioning a `message` parameter but that it was missing into the Swagger UI. Reading the description of this issue, it's in Swagger UI. So I've just rechecked and I confirm it's implemented into the endpoint: https://github.com/buddypress/BP-REST/blob/master/includes/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php#L361,L367

My bad 😞 . We can bring back the description of the message parameter of the `create_item` method into the documentation page.

BTW, we do have a UI to send a message when requesting to join a group, but it's only available from the group's single page, see screenshot below.

![message-request-membership](https://user-images.githubusercontent.com/1834524/81843427-de21d100-954d-11ea-8728-d040b4c15b36.png)

**Comment by renatonascalves** [comment]
Closing since the message was brought back in the documentation. :)
