### ISSUE TITLE
Permission checks when getting private group details

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#314]
This isn't so much an issue with the code but a question/discussion around the handling of permissions when getting group details via the get_items endpoint vs the get_item endpoint.

If I query the get_items endpoint (`/wp-json/buddypress/v1/groups`) while unauthenticated the response is:

```
{
  "id": 88,
  "creator_id": 922,
  "parent_id": 0,
  "date_created": "2020-05-12T05:04:41",
  "description": {
    "raw": "Private group desc.",
    "rendered": "<p>Private group desc.</p>\n"
  },
  "enable_forum": false,
  "link": "http://domain.test/groups/private-group/",
  "name": "Private group",
  "slug": "private-group",
  "status": "private",
  "types": [],
  "avatar_urls": {
    "full": "http://domain.test/wp-content/plugins/buddypress/bp-core/images/mystery-group.png",
    "thumb": "http://domain.test/wp-content/plugins/buddypress/bp-core/images/mystery-group-50.png"
  },
  "_links": {
    "self": [
      {
        "href": "http://domain.test/wp-json/buddypress/v1/groups/88"
      }
    ],
    "collection": [
      {
        "href": "http://domain.test/wp-json/buddypress/v1/groups/"
      }
    ],
    "user": [
      {
        "embeddable": true,
        "href": "http://domain.test/wp-json/buddypress/v1/members/922"
      }
    ]
  }
}
```

If I query the get_item endpoint (`/wp-json/buddypress/v1/groups/88`) while unauthenticated the response is:

```
{
  "code": "bp_rest_authorization_required",
  "message": "Sorry, you cannot view the group.",
  "data": {
    "status": 401
  }
}
```

This means through the list endpoint I can get private group details such as the creator, parent, date created and most importantly name, slug, description and avatar URLs whereas through the single group endpoint I cannot get any information regarding the group at all.

In my use case it would be really useful to still be able to get the same information in the single endpoint that you can in the list endpoint - the information is already exposed to an unauthenticated user.

Should the single endpoint be exposing the data and this is an issue?

**Comment by renatonascalves** [comment]
That's interesting! By default, the endpoint shouldn't be returning private groups. At least we are not doing anything to show it.

Let me do a few tests to confirm if that's a bug in the BP REST API code, BuddyPress or something on your end.

**Comment by sjregan** [comment]
My understanding is they should be returned by the list endpoint, this mirrors the behaviour of the front end.

Public and private groups can be seen in the group directory, hidden groups cannot.

**Comment by renatonascalves** [comment]
@imath That raises a good question! I'm inclined to say that those two should be the same. The current implementation takes into account endpoint access for the item where the `get_items` does not.

**Comment by sjregan** [comment]
Looking at the pull it looks like you are preventing private groups from being returned in the `get_items` endpoint, this is contrary to how the frontend works - is that intentional?

In the front end, unauthenticated and authenticated users can see private groups in the group directory (but not hidden ones). They need to be able to see them so they can request membership.

To expand upon my initial description of the issue, the issue also relates to authenticated users. An authenticated user can see the private group with `get_items` endpoint but cannot get the same group details with the `get_item` endpoint unless they are already member of the group.

This means it is not possible to fetch the group data (avatar, name, description etc) directly in order to present to the user whether they would like to join the private group not.

**Comment by renatonascalves** [comment]
About the PR, it is a suggestion. we are discussing with the team.

About this issue: I agree. Let's see what @imath has to say about it. Maybe there is a reason why it is this way that I don't remember.

:)

**Comment by imath** [comment]
Hi @renatonascalves I agree with @sjregan : basic information about the private groups should be returned by the 2 endpoints, otherwise it can be challenging to request a membership ;)

**Comment by renatonascalves** [comment]
@sjregan ^ Pull request above handles this issue.

**Comment by sjregan** [comment]
@renatonascalves Great, I'll check it out, thank you!

**Comment by renatonascalves** [comment]
@sjregan or @imath  Any feedback?

**Comment by sjregan** [comment]
@renatonascalves Outside of the items mentioned by imath it looks good to me :)
