### ISSUE TITLE
Check existing friendship before creating a new friendship request

### ISSUE THREAD

**Issue by ExoGeek** [buddypress/BP-REST#321]
Hello,

When creating a new friendship request (POST in friends enpoint), you should check if an existing request has already been made. Otherwize, multiple (duplicate) friendship requests are added to the database.

`POST {{host}}/wp-json/buddypress/v1/friends
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "friend_id": 24,
  "initiator_id": 1
}`

Ps : If you create multiple friendship requests via BP REST and then, you go on the website (frontend), the friend has to accept or reject the friendship multiple times ! This leads to weird behavior for user.

Regards
ExoGeek

**Comment by renatonascalves** [comment]
Taking a look...

**Comment by renatonascalves** [comment]
@ExoGeek Good catch! Tks for bringing that to my attention. I created a PR with unit tests with improvements and a fix for this bug. Feel free to test it. :)
