### ISSUE TITLE
Can not update a specific profile data

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#324]
Hello, I am using the example as shown in [here](https://developer.buddypress.org/bp-rest-api/reference/extended-profiles/profile-data/#save-a-specific-profile-data).

```
bp.apiRequest( {
  path: 'buddypress/v1/xprofile/6/data/1',
  type: 'POST',
  data: {
    context: 'edit',
    value: ['The field value']
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

This is working fine for all fields, except for **checkboxes** and **multiselectboxes**.

Is there a different way to update multiple values or is it something I am doing wrong?

Thank you in advance.

**Comment by renatonascalves** [comment]
Can you share an example of a field that's not working for you so that I can replicate?

**Comment by marioshtika** [comment]
Hello, @renatonascalves.

any update on this?

**Comment by marioshtika** [comment]
Hello, @renatonascalves.

Can you confirm if this is a bug, or is it something that I am doing wrong?

Thank you in advance.

**Comment by renatonascalves** [comment]
Sorry for the delay on this. Will take a look at this ASAP.

**Comment by renatonascalves** [comment]
I was able to confirm the bug. Still trying to find the source of the issue but something is parsing the values incorrectly in a way that a value like so: `value=Select 01` is being parsed into `["multiselectbox","01"]` instead of `["multiselectbox 01"]`.

**Comment by marioshtika** [comment]
Hello, @renatonascalves.

you are right. This issue happens only if the value has spaces in it.

It looks like the type `'array'` is causing the bug.
```
array(
    'methods'             => WP_REST_Server::EDITABLE,
    'callback'            => array( $this, 'update_item' ),
    'permission_callback' => array( $this, 'update_item_permissions_check' ),
    'args'                => array(
        'value' => array(
            'description' => __( 'The list of values for the field data.', 'buddypress' ),
            'type'        => 'array',
            'items'       => array(
                'type' => 'string',
            ),
            'arg_options' => array(
                'validate_callback' => 'rest_validate_request_arg',
                'sanitize_callback' => 'rest_sanitize_request_arg',
            ),
        ),
    ),
),
```

I have two suggestions:

**Suggestion 1:**
I tried `encodeURI()` on the value before sending it to the endpoint and it is splitting correctly but it is not recognizing it because it needs to be decoded on the other end.

**Suggestion 2:**
Don't let the args value type do the value split. It can be used as `type: 'string'` and then it can be exploded where `,` comma exists.

What do you think?

**Comment by renatonascalves** [comment]
@marioshtika ^ PR above has a fix for this issue. Feel free to test it.

**Comment by marioshtika** [comment]
Thank you @renatonascalves I tested it and it is working perfectly. 🚀 👍
