### ISSUE TITLE
Permission checks when getting single member item

### ISSUE THREAD

**Issue by sjregan** [buddypress/BP-REST#326]
This is a continuation of issue #314 - although rather than relating to the groups endpoint it relates to the members endpoint.

An unauthenticated user, using the `get_items` endpoint can retrieve member details such as:

- name
- user_login
- link
- member type
- xprofile data
- mention_name
- avatar URLs
- slug

However if an unauthenticated user uses the `/members/<id>` endpoint a `bp_rest_authorization_required` error is returned.

This creates odd situations such as an unauthenticated user being able to see the activity of a member, but not the member themselves.

**Comment by renatonascalves** [comment]
Tks for bringing this to my attention! We fixed in the commit above ^
