### ISSUE TITLE
Routes and endpoints for sending and receiving private message

### ISSUE THREAD

**Issue by 1geeky** [buddypress/BP-REST#33]
I couldn't find any route for posting and receive private messages.

In addition to primary fields, There should be the ability to add multi receivers, fetch or send attachments.

**Comment by renatonascalves** [comment]
@1geeky It wasn't built yet... It is in the roadmap. PR are very much welcomed! =)

**Comment by 1geeky** [comment]
@renatonascalves Where could I see the roadmap? Does it have any timing?
Maybe I'll do PR in future if it has not reached in the roadmap.

**Comment by renatonascalves** [comment]
@1geeky No timing yet! And PR are very much welcomed.

Also leave this issue open so that can we close it when this feature is added.

**Comment by 1geeky** [comment]
Sure

**Comment by renatonascalves** [comment]
Thank you!
