### ISSUE TITLE
Cannot post to group activity

### ISSUE THREAD

**Issue by scottopolis** [buddypress/BP-REST#334]
## Problem

I'm trying to post an activity update to a group through the activity endpoint, and it is not working. I have tracked the issue down to BuddyPress not using my group ID.

My request looks like this:

```
var settings = {
  "url": "https://MYSITEURL.com/wp-json/buddypress/v1/activity?component=activity&content=postman&context=edit&primary_item_id=1&type=activity_update",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Authorization": "Bearer XXXXXXXXXXXXX"
  },
};
```

I am using the JWT auth plugin for the rest api.

If you include a primary_item_id in your activity POST request, the activity endpoint fires groups_post_update(). 

```
                       if ( 'activity_update' === $type ) {
			if ( bp_is_active( 'groups' ) && ! is_null( $prime ) ) {
				$activity_id = groups_post_update( $prepared_activity );
			} else {
				$activity_id = bp_activity_post_update( $prepared_activity );
			}
```

In groups_post_update, the group ID is set to 0 by default: 

```
        $r = bp_parse_args( $args, array(
		'content'    => false,
		'user_id'    => bp_loggedin_user_id(),
		'group_id'   => 0,
		'error_type' => 'bool'
	), 'groups_post_update' );

	$group_id = (int) $r['group_id'];
	if ( ! $group_id && ! empty( $bp->groups->current_group->id ) ) {
		$group_id = (int) $bp->groups->current_group->id;
	}
```

In my case BuddyPress is not able to get my group ID that I sent with the request, it is always 0.

## Proposed solution

If the primary_item_id is included in the request, use that as the group ID in groups_post_update.  For example:

```
        $r = bp_parse_args( $args, array(
		'content'    => false,
		'user_id'    => bp_loggedin_user_id(),
		'group_id'   => ( isset( $args['primary_item_id']  ) ? $args['primary_item_id'] : 0 ),
		'error_type' => 'bool'
	), 'groups_post_update' );

```

Thanks

**Comment by scottopolis** [comment]
I just figured out that the problem is that I needed to change component to "groups" instead of "activity". This is not clear in the documentation, might want to add that.

**Comment by imath** [comment]
Hi Scott, I agree, I’ll update the documentation 👍

imath
https://imathi.eu
________________________________
De : Scott Bolinger <notifications@github.com>
Envoyé : Wednesday, July 8, 2020 8:02:23 PM
À : buddypress/BP-REST <BP-REST@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [buddypress/BP-REST] Cannot post to group activity (#334)


Problem

I'm trying to post an activity update to a group through the activity endpoint, and it is not working. I have tracked the issue down to BuddyPress not using my group ID.

My request looks like this:

var settings = {
  "url": "https://MYSITEURL.com/wp-json/buddypress/v1/activity?component=activity&content=postman&context=edit&primary_item_id=1&type=activity_update",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Authorization": "Bearer XXXXXXXXXXXXX"
  },
};


If you include a primary_item_id in your activity POST request, the activity endpoint fires groups_post_update().

                       if ( 'activity_update' === $type ) {
                        if ( bp_is_active( 'groups' ) && ! is_null( $prime ) ) {
                                $activity_id = groups_post_update( $prepared_activity );
                        } else {
                                $activity_id = bp_activity_post_update( $prepared_activity );
                        }


In groups_post_update, the group ID is set to 0 by default:

        $r = bp_parse_args( $args, array(
                'content'    => false,
                'user_id'    => bp_loggedin_user_id(),
                'group_id'   => 0,
                'error_type' => 'bool'
        ), 'groups_post_update' );

        $group_id = (int) $r['group_id'];
        if ( ! $group_id && ! empty( $bp->groups->current_group->id ) ) {
                $group_id = (int) $bp->groups->current_group->id;
        }


In my case BuddyPress is not able to get my group ID that I sent with the request, it is always 0.

Proposed solution

If the primary_item_id is included in the request, use that as the group ID in groups_post_update. For example:

        $r = bp_parse_args( $args, array(
                'content'    => false,
                'user_id'    => bp_loggedin_user_id(),
                'group_id'   => ( isset( $args['primary_item_id']  ) ? $args['primary_item_id'] : 0 ),
                'error_type' => 'bool'
        ), 'groups_post_update' );



Thanks
