### ISSUE TITLE
Is there a way to access posts from a group?

### ISSUE THREAD

**Issue by kallewesterling** [buddypress/BP-REST#338]
I am unable to find information about whether there is a way to find all the posts in a specific group (for which I have the ID). When requesting (`GET`) `/wp-json/buddypress/v1/groups/<id>` I can only see meta data about the group, no posts.

**Comment by kallewesterling** [comment]
Thank you so much for the answer @renatonascalves !

**Comment by hinnerkweiler** [comment]
May I suggest adding a hint somewhere to the `groups` endpoint documentation. I remember searching the web up and down for about two days myself on how to get access to a group's content before even looking at other endpoints like `activity`.

From a developers view it is logical now to me, that group activities are basically just activities in a certein context. However it was not intuitive to me at all and I assume many people would expect group content to be found somewhere like `buddypress/v1/groups/<id>/posts`. Pointing these people to the right endpoint may be worth a line of documentation.  

However, thanks for the great API

**Comment by renatonascalves** [comment]
@imath will take care of updating the documentation. :)

**Comment by imath** [comment]
I've just updated the documentation 😉 

See https://developer.buddypress.org/bp-rest-api/reference/user-groups/groups/#retrieve-a-specific-user-group
