### ISSUE TITLE
List activities from multiple types

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#345]
I am trying to get activities from multiple types by adding two activity types on the `type` parameter

```
type: 'activity_update,new_blog_post',
```

I am using the below code:

```
bp.apiRequest( {
  path: 'buddypress/v1/activity',
  type: 'GET',
  data: {
    context: 'view',
    type: 'activity_update,new_blog_post',
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

The response to that above call is:

```
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): type",
    "data": {
        "status": 400,
        "params": {
            "type": "type is not one of new_member, new_avatar, updated_profile, activity_update, activity_comment, friendship_accepted, friendship_created, created_group, joined_group, group_details_updated, new_blog_post, new_blog_comment."
        }
    }
}
```

Is this something that is not supported, or am I doing something wrong? I couldn't find any reference on the documentation.

Thank you in advance.

**Comment by imath** [comment]
Shouldn’t the activity type of the request be an array instead of a csv string ?

imath
https://imathi.eu
________________________________
De : Renato Alves <notifications@github.com>
Envoyé : Wednesday, July 22, 2020 7:39:45 PM
À : buddypress/BP-REST <BP-REST@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [buddypress/BP-REST] List activities from multiple types (#345)


This is likely a bug in how the value is being sanitized at the BP REST API. Will investigate.

**Comment by renatonascalves** [comment]
ˆabove PR changes the param from a string into an array. Documentation will need to be updated here, https://developer.buddypress.org/bp-rest-api/reference/activity/#arguments, to account for this change.

In practice, this will still work (tested locally):

```
bp.apiRequest( {
  path: 'buddypress/v1/activity',
  type: 'GET',
  data: {
    context: 'view',
    type: 'activity_update,new_blog_post',
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

**Comment by renatonascalves** [comment]
@imath that needs a update in the documentation. Do you usually update that now or after 7.0 is release?

**Comment by imath** [comment]
Thanks for the ping. Let's keep it open with the Documentation label on to keep it in mind, once 7.0.0 will be RC.

**Comment by imath** [comment]
Just updated https://developer.buddypress.org/bp-rest-api/reference/activity/#arguments according to these changes.
