### ISSUE TITLE
Change default repo branch from master to main

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#349]
As mentioned in the previous dev chat, I'd like to move the current branch name from `master` into `main`.

I already created the `main` branch and there are two tasks pending for this migration:

- change the default branch to the main one.
- Remove `master` branch

**Comment by renatonascalves** [comment]
@imath Do you see any possible drawback from making this change?

**Comment by imath** [comment]
Hi @renatonascalves I advise you to make sure the BuddyPress `grunt build` command downloads the `main` branch before deleting the `master` one.

If so, go ahead 😉
