### ISSUE TITLE
Get the Notification's sender avatars

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#360]
GET /buddypress/v1/notifications
the avatar_urls object contains the paths to the full and thumb avatar of the RECIPIENT. What I expect is that the avatar should be of the notification SENDER, that is the user who fired the action.
Buddypress version: 6.3.0
BP REST API version: 0.3.0

See https://buddypress.trac.wordpress.org/ticket/8385

**Comment by renatonascalves** [comment]
Maybe both?

**Comment by imath** [comment]
Yes the need is to have both recipient and sender ;)

**Comment by renatonascalves** [comment]
Am I correct they are talking about the Messages instead of the Notifications component? Otherwise that doesn't make sense since there is no sender and recipient for the notifications component.

**Comment by imath** [comment]
I think it's about specific notifications eg: "imath invited you to join the group"

**Comment by renatonascalves** [comment]
What I meant is that currently, there is no user avatar being displayed in the notification endpoint. Nothing from the sender or the recipient. But in the ticket, they are mentioning of seeing the avatar from the recipient. Which is odd!

**Comment by imath** [comment]
You're right, and we can get the sender's avatar using the recipient list into the messages endpoint. I've commented on the Trac ticket to get the reporter's feedback: https://buddypress.trac.wordpress.org/ticket/8385#comment:2

**Comment by renatonascalves** [comment]
Tks for the feedback there! :)

**Comment by renatonascalves** [comment]
Closing this one for now since it seems invalid. Feel free to reopen after the reporter provides more feedback about the issue. :)
