### ISSUE TITLE
You can make a friend request to yourself from someone else...

### ISSUE THREAD

**Issue by dominic-ks** [buddypress/BP-REST#369]
I've just found that you can make a friend request from someone else to yourself, if you send a post request to `/buddypress/v1/friends` with a body like this:

```
{
    initiator_id: 1, //this is the user I am logged in as and I am the initiator in the resulting friendship
    friend_id: 2, //this is my potential new friend and is the friend in the resulting friendship
}
```

Which works fine, but if I do this:

```
{
    initiator_id: 2, //this is my potential new friend and is the initiator in the resulting friendship
    friend_id: 1, //this is the user I am logged in as and I am the friend in the resulting friendship
}
```

As user with ID 1, I am then able to accept the friendship request from user with ID 2 even though I am the one who made the request.

**Comment by renatonascalves** [comment]
Ops! I was able to confirm this... sorry... working on a patch to fix it.

**Comment by dominic-ks** [comment]
Cheers for the update!
