### ISSUE TITLE
Activities Not Returning Media

### ISSUE THREAD

**Issue by lavation** [buddypress/BP-REST#376]
New to this api and I have everything working mostly as I would expect but when I return the activities, the content rendered is lacking any media they uploaded in the post. I'm not seeing anything in the documentation nor past issues on here so any guidance on what I should be doing would be appreciated :D

**Comment by renatonascalves** [comment]
Could you share the actual and expected output?

**Comment by lavation** [comment]
Thanks for your quick reply. As I investigated more, it looks like the media isn't part of the standard buddypress but rather part of a plugin called youzify  / yz-post-attachments

So I guess I need to figure out how to extend the api to include these attachments.

**Comment by renatonascalves** [comment]
Ok! We have some docs that might help you in extending the endpoint: https://developer.buddypress.org/bp-rest-api/extending-the-bp-rest-api/

:)
