### ISSUE TITLE
Move CI from Travis to Github Actions

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/BP-REST#377]
as titled.

**Comment by renatonascalves** [comment]
@imath any objections to that move?

**Comment by imath** [comment]
Hi @renatonascalves on the contrary 😊. You have my full support to do this move. FYI, I shared a patch about doing this move for BuddyPress : https://buddypress.trac.wordpress.org/ticket/8421

**Comment by renatonascalves** [comment]
That's awesome! I wasn't aware of that. Going to take a look! :)
