### ISSUE TITLE
Mark private message as read

### ISSUE THREAD

**Issue by tkserver** [buddypress/BP-REST#390]
I don't see anywhere in the buddypress rest api to set a private message as read.  Am I missing something?

**Comment by renatonascalves** [comment]
No! That's not available currently. You can't mark a message or a thread as (un)read via the REST API right now.

**Comment by tkserver** [comment]
Thanks for the response! Apologies for the thumbs down but this puts a real monkey wrench in my app development.  When a user in my app reads his mail, it should be marked as read!   I guess I'll have to make my own endpoint.

**Comment by renatonascalves** [comment]
I understand the frustration. This is actually in our plans to support. We just have been focusing in other things and left this one to "last".

:)

**Comment by dcavins** [comment]
@tkserver You can always submit a pull request with a patch! :)

**Comment by renatonascalves** [comment]
I'm working on the implementation of this feature. :)

**Comment by tkserver** [comment]
@renatonascalves nice. Can't wait to see it.

I had to make my own endpoint so I could finish the version of my react native app.
