### ISSUE TITLE
Add gmt date in activity, notifications and messages endpoints

### ISSUE THREAD

**Issue by Achilles4400** [buddypress/BP-REST#417]
is it possible to add the gmt date for every date field in activity, notifications, messages endpoints ?

an example on messages endpoint add date_gmt, start_date_gmt, date_sent_gmt etc...

**Comment by renatonascalves** [comment]
I think that's a nice addition. Will be introducing that soon. Tks for the suggestion!

**Comment by renatonascalves** [comment]
We can easily support this here but I created a ticket at BuddyPress core to properly support this there: https://buddypress.trac.wordpress.org/ticket/8536

**Comment by renatonascalves** [comment]
@Achilles4400 Did you notice that all dates are already on GMT?
