### ISSUE TITLE
Latest Stable Version?

### ISSUE THREAD

**Issue by dominic-ks** [buddypress/BP-REST#42]
Sorry to leave this here, but didn't know where else I could get in contact. Having trouble hunting down the latest stable version (or any) of the plugin on wp.org as mentioned in the readme.

Could someone please provide a link?

**Comment by renatonascalves** [comment]
It doesn't exist yet! There are people forking and working on their own branches. But we still don't have a stable version.

**Comment by dominic-ks** [comment]
Right thanks for that! Not sure why it mentions this in the readme then, but hey ho.
