### ISSUE TITLE
Can not update profile data for checkboxes and multiselectboxes.

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#424]
I had the same problem a while ago, as mentioned in the below issue:
https://github.com/buddypress/BP-REST/issues/324

It was fixed back then, but now it is not working again. I don't know if some of the previous versions broke this.

Write now it is working with all fields data types, except checkboxes and multiselectboxes.

And it is not working with values with spaces or without spaces.

Thank you in advance.

**Comment by marioshtika** [comment]
On profile fields, I added a new field in the `Multi Fields` tab

<img width="368" alt="1" src="https://user-images.githubusercontent.com/3079663/84285804-95f2d000-ab46-11ea-998e-391d85cf9ff1.png">

I created a multiselectbox

<img width="298" alt="2" src="https://user-images.githubusercontent.com/3079663/84286017-ce92a980-ab46-11ea-8aab-793790bfe2bb.png">

Then I used the below endpoint to update the field data (24 is the user_id)

```
/wp-json/buddypress/v1/xprofile/16/data/24?value=multiselectbox 1
```

and the response is 

```
[{
    "id":231,
    "field_id":16,
    "user_id":24,
    "value":{
        "raw":"a:0:{}",
        "unserialized":[],
        "rendered":"<p><a href=\"https:\/\/___mysite____\/members\/?members_search\" rel=\"nofollow\"><\/a><\/p>\n"
    },
    "last_updated":"2021-10-12T17:36:55",
    "_links":{
        "self":[{
            "href":"https:\/\/____mysite____\/wp-json\/buddypress\/v1\/xprofile\/16"}],
            "user":[{
                "embeddable":true,
                "href":"https:\/\/app2you.eu\/wp-json\/buddypress\/v1\/members\/24"
        }]
    }
}]
```

**Comment by marioshtika** [comment]
Hello @renatonascalves and @imath 

I can confirm that this is working.

Thank you

**Comment by buchi-1996** [comment]
Please guys I'm faced with the same issue, are there any tips on how to implement the working solution??.

I tried updating a multiselect field using the api https://createm8.com/wp-json/buddyboss/v1/xprofile/7/data/1.

But I get this response.

`{
    "id": 9,
    "field_id": 7,
    "user_id": 1,
    "value": {
        "raw": "a:0:{}",
        "unserialized": [],
        "rendered": ""
    },
    "last_updated": "2023-05-05T11:24:34",
    "_links": {
        "self": [
            {
                "href": "https://createm8.com/wp-json/buddyboss/v1/xprofile/7"
            }
        ],
        "user": [
            {
                "embeddable": true,
                "href": "https://createm8.com/wp-json/buddyboss/v1/members/1"
            }
        ]
    }
}`

**Comment by imath** [comment]
Hi @buchi-1996 

The BP Rest API is being maintained by the BuddyPress team, we cannot help you for a trouble you have with a fork of BuddyPress, please contact this fork support/developer team. 

PS: our endpoints are all containing `buddypress` unlike the one you shared.
