### ISSUE TITLE
Filter members by xprofile field

### ISSUE THREAD

**Issue by jakubrak** [buddypress/BP-REST#425]
Documentation states that result of querying list of members can be limited by xprofile field of string type:

https://developer.buddypress.org/bp-rest-api/reference/members/#arguments

however there is no information about string format. My suspcion is it has never worked, since BP_XProfile_Query expect an array, not a string: 
https://github.com/buddypress/BuddyPress-build/blob/master/bp-xprofile/classes/class-bp-xprofile-query.php#L59

I am right? If so, at least documentation should be clear that it is not implemented.

**Comment by adiloztaser** [comment]
Hi @jakubrak,

I think you right. `xprofile` parameter type should be array. I've created a PR for this, let's wait @imath and @renatonascalves response.
