### ISSUE TITLE
Rest API for group activity 

### ISSUE THREAD

**Issue by Emon69420** [buddypress/BP-REST#431]
Hello, I have been to 4 different forums and I still don't have an answer so I thought asking the actual developers, I want to get all the activity (updates, comments, etc) of all the groups joined by the logged in user using the rest api, can bp rest api do this?

**Comment by renatonascalves** [comment]
Yeah, you can't get all of that information from a single request and single endpoint. I can think of two options you can take.

1st - You can get all the groups the user joined from the Groups endpoint, see an example here: https://developer.buddypress.org/bp-rest-api/reference/user-groups/groups/#example-of-use

And get the updates and comments using the Activity endpoint: https://developer.buddypress.org/bp-rest-api/reference/activity/#list-activities using the group ID from the previous list. 

You would need to keep track of those group IDs in your app. And handle the second request for the Activity endpoint.

2nd - Another option you can take is by hooking into `bp_rest_groups_prepare_value` (This hook is run for every group that's returned in the Groups endpoint) and append another key for the activities of the group.

This however might introduce lots of issues, mostly pagination, bigger response size and you won't have the flexibility that the Activity endpoint provides.

---

So the answer to your question is no. You can't get activity updates/comments from all groups a user is joined from a single endpoint by default. And we don't have any plans of introducing that in the BP REST API.

Hope that helps.

Note: I'll be closing this issue. :)
