### ISSUE TITLE
Can not get invite_id for hidden groups

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#432]
Hello,

I am trying to use the endpoint that can accept or reject an invitation from a hidden group. But I have to send the `invite_id` to make that request.

But I think there is no way to retrieve or find the `invite_id`. 

I would expect:
1. to see it on the notification endpoint (on the notification when someone has invited me to a hidden group).
2. or else to get it from an endpoint where I can get all my invites (and maybe filter by the group id)

None of the above have that information.

Can you help me find out, how can I get that information, or see if we can find a way to add that information?

Thank you in advance.

**Comment by renatonascalves** [comment]
Hi!

1 - I might be wrong here but I think the `invite_id` in the notification object is the `item_id` or the `secondary_item_id`.
2 - You can actually get group invites using this endpoint: https://developer.buddypress.org/bp-rest-api/reference/user-groups/group-invites/#list-the-group-invites The output returns an `id` for every single invitation.

**Comment by marioshtika** [comment]
@renatonascalves thank you for the response.

The `invite_id` does not exist in the notification object.
Neither `item_id` nor `secondary_item_id` is showing the value of `invite_id`

I can confirm that the group invite endpoint can retrieve that information but for me, it is not the solution I was looking for.
So I created a filter for `bp_rest_notifications_prepare_value` and added the `invite_id` when it is needed.

Thank you again for your time.
