### ISSUE TITLE
List user groups including hidden groups is not working for non administrator

### ISSUE THREAD

**Issue by marioshtika** [buddypress/BP-REST#433]
Hello,

I want to get all the groups and I am using the `GET /buddypress/v1/groups` endpoint as shown in the [documentation](https://developer.buddypress.org/bp-rest-api/reference/user-groups/groups/#list-user-groups)

I want to include hidden groups too, so I am adding the `show_hidden=true` parameter.

```
bp.apiRequest( {
  path: 'buddypress/v1/groups',
  type: 'GET',
  data: {
    context: 'view',
    show_hidden: true
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

This is working fine if I am the creator of the hidden group.

If the user making the request is a member of the hidden group (and not the creator) the hidden group will not show in the response.

Any idea, why this is happening?

Thank you in advance.

**Comment by renatonascalves** [comment]
This is happening because you are not setting the `user_id` param. This param is required when you are trying to get groups from a specific member. Internally, we check if the `user_id` is the same as the current logged in user. If they are, we include hidden or private groups.

This is necessary because this endpoint can return public groups even for non-logged in users.

**Comment by marioshtika** [comment]
Hello @renatonascalves and thank you for your answer.

I will try to explain my scenario and let me know if there is something I am doing wrong or if this is not the proper behavior.

If I use the `user_id` parameter it will show me the groups I am a member of.

What I want to achieve is getting all groups available to me and if I want to use `show_hidden: true` I would expect as an addition to my available groups to see the hidden groups I am a member of.

Here is an example of my scenario

I have four groups
- Group 1 (public) - I am a member of this group
- Group 2 (public) - I am **not** a member of this group
- Group 3 (private) - I am a member of this group
- Group 4 (hidden) - I am a member of this group

If I retrieve all groups, without `show_hidden: true` it will show me 
- Group 1
- Group 2
- Group 3

If I retrieve all groups, with the `show_hidden: true` it will show me again 
- Group 1
- Group 2
- Group 3

_It will not show me Group 4_

If I retrieve all groups, with the `show_hidden: true` and `user_id: ___` it will show me 
- Group 1
- Group 3
- Group 4

_It will not show me Group 2 which is public_

Is there anything we can do for this scenario?

Thank you in advance

**Comment by renatonascalves** [comment]
If you are returning all groups you are a member (when you use the `user_id` parameter, that's what you are doing), you won't have public groups where **you are not** a member that group.

Solution: You could be a member of Group 2 and it would appear in the list with the rest of the groups.

**Comment by marioshtika** [comment]
Thank you @renatonascalves,

I understand that and yes it will appear in the list if I am a member.

I am using the BuddyPress API on a mobile application and I was thinking that there is no direct endpoint (or combination of parameters) to check all my **available** groups (public, private and hidden)

I think `show_hidden` parameter should be working on its own (or in combination with the default parameter) and not in combination with `user_id`. Because this way it is making the `show_hidden` parameter very limited.

What do you think of this way of thinking? Is this something it can be considered?

Thank you again.

**Comment by renatonascalves** [comment]
Unlikely something we will consider to BuddyPress core. An endpoint that returns all available groups regardless of its status is dangerous to put in the plugin.

I don't know how exactly your app will use this list but think of a scenario of a user authenticated in your app (he is not an admin). If we add an endpoint, or change the current one to permit this, to get all available groups, this could be misused, besides the act of broadcasting information which are inherently _hidden_ or private.

I'm not saying that's not possible technically. I'm saying that for a core endpoint, this would be a counterintuitive feature to add. One that does not mirror BuddyPress itself (outside of API).

You could however filter `bp_rest_groups_get_items`, get all the groups directly, via a SQL command for example, and return all groups for specific users or whatever how you want to present this information.

https://github.com/buddypress/BP-REST/blob/6db9d8ceaf5cba53d80d968823107488d5d85fcd/includes/bp-groups/classes/class-bp-rest-groups-endpoint.php#L200

@imath I'd love your thoughts on this one.

**Comment by imath** [comment]
Hi @renatonascalves 

Thanks for pinging me about it. I'll try to rephrase @marioshtika expectation to make sure I fully understand the point:

You need to get all public/private groups + the hidden groups the current user is a member of? Do I got it right?

**Comment by renatonascalves** [comment]
It seems he wants to get all public/private groups + the hidden groups of the current member + the public groups the user **is not** a member.

```
If I retrieve all groups, with the show_hidden: true and user_id: ___ it will show me

Group 1
Group 3
Group 4
It will not show me Group 2 which is public
```

**Comment by marioshtika** [comment]
Hello everyone.

@imath yes you are right. 
I am trying to get all public/private groups + the hidden groups the current (logged in) user is a member of.
So I would expect to see those groups if I add the `show_hidden` parameter and if I am logged in.

@renatonascalves I am sorry I overanalysed it 😄  when trying to explain it.
I am not trying to get the groups of the given member including their hidden groups. I am trying to get the available groups  of the logged in user (including their hidden groups)

If you want and if it helps I can send a pull request with what I am suggesting.

**Comment by imath** [comment]
Hello @marioshtika 

Thanks for your confirmation, you'll need to run 2 queries to achieve this. The regular one will give you all public & private groups. Then, you can filter `groups_get_groups` to surcharge groups with the hidden ones of the current logged in user.

Something like:

```php
function marioshtika_get_groups( $groups = array(), $query_args = array() ) {
    if ( ! is_user_logged_in() ) {
        return $groups;
    }

    $hidden_groups = groups_get_groups(
        array(
            'user_id' => bp_loggedin_user_id(),
            'status'  => 'hidden',
        )
    );

   $groups['groups'] = array_merge( $groups['groups'], $hidden_groups['groups'] );

   return $groups;
}
add_filter( 'groups_get_groups', 'marioshtika_get_groups', 10, 2 );
```
I can see a pagination nightmare to deal with in doing this 😬 .

It's looking like sticky posts, having the possibility to stick one or more activities/groups/members at the top of the corresponding loops would probably be a nice feature to have in BuddyPress core! Don't hesitate to suggest a patch there: https://buddypress.trac.wordpress.org/newticket

**Comment by renatonascalves** [comment]
@marioshtika 

> I am trying to get all public/private groups + the hidden groups the current (logged in) user is a member of.

This is already happening/working and we have even unit tests setup for that: https://github.com/buddypress/BP-REST/blob/master/tests/groups/test-controller.php#L66-L96.

Which tells me you are doing something wrong. Could you share your request with the paremeters being used?

**Comment by renatonascalves** [comment]
Just to be clear. This won't work:

```

bp.apiRequest( {
  path: 'buddypress/v1/groups',
  type: 'GET',
  data: {
    context: 'view',
    show_hidden: true // the user_id paremeter is missing here and it is required to get groups from a specific user.
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

This is the correct way to get groups from a specific user, including hidden groups.
```
bp.apiRequest( {
  path: 'buddypress/v1/groups',
  type: 'GET',
  data: {
    context: 'view',
    show_hidden: true
    user_id: the ID of the user
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );

```

**Comment by renatonascalves** [comment]
Even if you are logged in, you need to pass the `user_id` paremeter.

**Comment by marioshtika** [comment]
@imath thank you for the help and your time.
@renatonascalves thank you for the clarification and your time.

I thought it was something wrong with the API response but now I understand that this is how the BuddyPress core functionality works.

Is this something you will consider adding as a feature on future releases?
I have seen this solution on other forks of the BuddyPress repository.
If you do, you can let me know and I can help with sending a pull request with a possible solution.

Thank you in advance
