### ISSUE TITLE
profile fields do not return data when Everyone visibility is not selected in visibility setting

### ISSUE THREAD

**Issue by modemlooper** [buddypress/BP-REST#435]
When you choose any option other than Everyone  visibility for a profile field the api doesn't return the field data using fetch_field_data = true.

I have authorization via JWT and pass in the user_id.

> GET /wp-json/buddypress/v1/xprofile/fields/?fetch_field_data=true&user_id=180&hide_empty_fields=false HTTP/2
> Host: ygm.local
> user-agent: insomnia/2021.6.0
> cookie: PHPSESSID=cbec622a2dfacee71a5b77d847e260fb
> authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveWdtLmxvY2FsIiwiaWF0IjoxNjM5ODY4MTg5LCJuYmYiOjE2Mzk4N]6SIB_s
> accept: */*

**Comment by renatonascalves** [comment]
Interesting! Let me see if I can reproduce that.

**Comment by modemlooper** [comment]
I need to test more because it could be something causing it. There was an issue with some endpoints that didn't respect auth based on what hook the code was loaded on. It might be the same issue. It could be the member types pro plugin causing it. They have an option to show different fields based on member type. 

I found a couple other bugs but hey are fixed in repo but not in release yet.

**Comment by renatonascalves** [comment]
Understood! Let me know if you need me to investigate it further. :)

**Comment by modemlooper** [comment]
It's something to do with hook priority, I need to set up a fresh install and test...

**Comment by modemlooper** [comment]
Ok, so I'm going close this. It was definitely a priority issue. But it's strange that it was only for certain endpoints.

**Comment by renatonascalves** [comment]
If you think there is something we can do to avoid this, let us know.
