### ISSUE TITLE
How exactly is this installed?

### ISSUE THREAD

**Issue by riveraj33** [buddypress/BP-REST#436]
I thought it's just a simple plug-in to drop in the wp plug-in folder and activate but my app dev isn't able to access the api. Is there something im missing? TYIA

**Comment by renatonascalves** [comment]
Have you got BuddyPress installed?

**Comment by riveraj33** [comment]
Hello. Yes buddy press is installed and activated as is this plug-in. But when trying to access the api from a url, nothing. I've used this endpoint 
/buddypress/v1/groups 
at the end of my site url.

**Comment by renatonascalves** [comment]
Here is an example of how you can access it: https://site.com/wp-json/buddypress/v1/groups/

I also recommend our documentation for more details: https://developer.buddypress.org/bp-rest-api/
