### ISSUE TITLE
Create new activity for a group is throwing error.

### ISSUE THREAD

**Issue by gogobody** [buddypress/BP-REST#438]
```
POST:
https://www.mysite.com/wp-json/buddypress/v1/activity

HEADER:
Authorization : Bearer xxxxx

DATA:
component : groups
primary_item_id : 3
content: <a>xxx</a><br><a>ccc</a>
```
 I got error when I did this using python-requests.

`{'code': 'bp_rest_user_cannot_create_activity', 'message': '无法创建新活动。', 'data': {'status': 500}}`

Then, I found that the msg can post success when I remove `<br>` from my content.

So I tried replace `<br>` to `\n` (`<p>`)  and then the error appears.

So how can I send line feed correctly?

plz help.

**Comment by gogobody** [comment]
I don't know why. I just want to send some HTML with links. I tried to send some strings, and it is correct to use `\n` newline.

**Comment by renatonascalves** [comment]
Hey, @gogobody Yeah! Closing this issue as invalid since this is standard behavior even outside of the API context, front-end.
