### ISSUE TITLE
Get activity with comments

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#439]
Hi, sorry for putting my question here, I try to not, but I couldn't find an answer anywhere

I'm building an app for BuddyPress, but my problem now is how to get the activity comments and how to post a comment to an activity through the REST API

1-What’s the REST API endpoint to get activity with comments(please provide an example how to use the parameter display_comments), Or what’s the endpoint to get comments?
I’m using this endpoint: https://example.com/wp-json/buddypress/v1/activity
 getting the last 10 activity but no comments are associated

2-how to post a comment to an activity through the REST API

I’m using the latest WordPress and BuddyPress version and have no problems, everything works great,

thanks

**Comment by renatonascalves** [comment]
Hello!

1 - To get activities with their comments, see the endpoin: https://developer.buddypress.org/bp-rest-api/reference/activity/#list-activities See the `display_comments` paremeter.

2 - Here is the documentation of a POST request: https://developer.buddypress.org/bp-rest-api/reference/activity/#create-an-activity
