### ISSUE TITLE
Retrieve a specific Profile Data correcting the endpoint in documentation

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#442]
Hi first thank you for this great work

I was trying to Retrieve a specific Profile Data  user information 
flowing documentation, but the path was not working

then I notice there was a misspelling typing the right endpoint, in the documentation if it is the case can you please fix it

Didn't work
GET /buddypress/members/me

Works
GET /buddypress/v1/members/me

[Retrieve a specific Profile Data](https://developer.buddypress.org/bp-rest-api/reference/members/#retrieve-the-logged-in-member)

**Comment by imath** [comment]
Hi @ranfen 

Thanks for your feedback, I've just updated the documentation.
