### ISSUE TITLE
Add links for item available actions

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#444]
I'm currently working on adding a BP reNouveau template pack in BP 11.0.0. This template pack will only use the BP REST API. So I'll probably report other possible improvements.

This one is about being able to get the endpoint for action concerning a member item of a members loop (eg: the endpoints to add friend/cancel friendship)

I see the WP Posts REST Controller is adding "self" links to add available actions, see https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1939|L1947

It would be very useful to have this kind of functionality for members actions, but also for other component items (activity, group..) actions.

**Comment by renatonascalves** [comment]
Agree! This is a low-effort addition.

**Comment by imath** [comment]
Awesome, do you have time to work on it?

**Comment by renatonascalves** [comment]
I do!

**Comment by renatonascalves** [comment]
@imath Just to clarify something. In some of our controllers, we are already providing links to access other related endpoints. Not all controllers have it available and we can expand on that as part of this issue.

However, we are not introducing this https://github.com/WordPress/wordpress-develop/blob/ab2cd6f03b591c773ae84db338d437d6cff376a4/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L2112-L2158 which seems to be adding and it is visible [together with the schema](https://github.com/WordPress/wordpress-develop/blob/ab2cd6f03b591c773ae84db338d437d6cff376a4/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L2605-L2619).

I'm actually not sure how those `https://api.w.org` links are related to the `prepare_links` we need to add.

**Comment by imath** [comment]
Sorry for the `api.w.org` thing, you're right, the best is to add new entries inside the `self` array making sure to identify the action eg: 

```php
		$self[] = array(
			'action' => $data['friendship_status_slug'],
			'href'   => trailingslashit( $base_url ) . $data['id'],
		);
```

**Comment by renatonascalves** [comment]
After looking briefly at what WordPress core is doing, I think I'm starting to understand what's happening there. So the goal is:

- Add a schema link for the new action. Explaining what the action does. [Here is an example](https://github.com/WordPress/wordpress-develop/blob/ab2cd6f03b591c773ae84db338d437d6cff376a4/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L2621-L2635).
- Introduce the link itself. See example below.

```
$self['https://api.w.org/action-activity-delete'] = array(
	'href'=> trailingslashit( $base_url ) . $data['id'],
);
```

They are using this approach to create the rel, `https://api.w.org/action-activity-delete`. We can follow this practice or create something custom or unique to our use case. The response will be converted into something like this:

```

"wp:action-activity-delete": [
    {
        "href": "https://site.com/wp-json/buddypress/v1/activity/12328934687234"
    }
],
```

**Comment by renatonascalves** [comment]
I actually think we can skip the schema part since we already don't introduce for the current links.

**Comment by imath** [comment]
Instead of "wp:action", can we have "bp:action" ?
