### ISSUE TITLE
Activity `update_item()` method needs improvements

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#446]
I'm also working on the Activity Block Editor and noticed 2 possible improvements: 

1. the date is not kept although I've sent it. This can be annoying if an Admin edits the activity of another user. In other words in the edited activated date was 'before' using `update_item()` makes it become 'now'. I believe it's in the method to prepare the item for the database the fix needs to happen.
2. When updating an activity about a group, `groups_record_activity()` should be used to make sure activity about non public groups have their visibility unchanged. In one of my tests, when I've updated a public "my profile" activity to attach it to a private group, the visibility of this activity wasn't hidden but public.

Thanks in advance for your help 😄

**Comment by renatonascalves** [comment]
I'll look into it. Keep the bug reports coming. 💯

**Comment by renatonascalves** [comment]
1 - I confirmed it and I sent a patch in the pull request above. ☝🏽 But I think what you really want is to NOT UPDATE when an admin is updating an activity.
