### ISSUE TITLE
Extending the BP REST API

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#449]
Hi I wanted to register a REST field for the Activity Endpoints to get the username of the activity post creator, but I didn’t know how to implement it, I pasted this code [(Extending the BP REST API)](https://developer.buddypress.org/bp-rest-api/extending-the-bp-rest-api/) in the function.php, but I’m not getting anything back, any help please where this piece of code should be put? Which function.php and how to return the username any help or guidance please

**Comment by renatonascalves** [comment]
@ranfen I'm able to use the provided function in that documentation article and get the proper response. I'm closing this issue as invalid but feel free to share here any feedback or more information that might indicate it is a bug.

:)
