### ISSUE TITLE
Upload failed! Error was: Invalid form submission..

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#451]
Hi i fellowed the documentation to upload a user avatar thought the rest API but its not working i get this error

deleting avatar and  getting avatr works but upload give me this error im i doing something wrong? 

    "code": "bp_rest_attachments_user_avatar_upload_error",
    "message": "Upload failed! Error was: Invalid form submission..",
    "data": {
        "status": 500,
        "reason": "upload_error"
    }

![iScreen Shoter - 2022-08-01 12:42:09 520](https://user-images.githubusercontent.com/80561800/182200321-2ec047d3-3cbe-4ce3-ae3d-dd6c565632a2.jpg)

**Comment by imath** [comment]
Hi @ranfen 

You need to send a POST form data to have it working see the example of code available here: https://developer.buddypress.org/bp-rest-api/reference/attachments/member-avatar/#attach-an-avatar-to-a-member

**Comment by renatonascalves** [comment]
Closing this issue as invalid. Feel free to ping us again with new information. :)
