### ISSUE TITLE
Is there is a way to check if a member already messaged another member? 

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#455]
Using REST API endpoint Is there is a way to check if a member already messaged another member? Or they never messaged each other?

We already check the documentation, but we can't find a special endpoint for it

thanks

**Comment by renatonascalves** [comment]
No endpoint performs this specific check, but I think you can use https://developer.buddypress.org/bp-rest-api/reference/private-messaging/#list-messages-threads to get a user list of thread messages and compare it against this other user.

**Comment by ranfen** [comment]
> No endpoint performs this specific check, but I think you can use https://developer.buddypress.org/bp-rest-api/reference/private-messaging/#list-messages-threads to get a user list of thread messages and compare it against this other user.

Thank you for the answer,
 for now that what we are planning to do, but the problem is if the: get user list of threads only give last 10 threads and the thread with user we are trying to compare against is not returned in the last 10, this way we will not be able to make sure if there was a thread and I don't see a way to get second page for list of threads like we do in activities, even if there is a way it will be not good idea to keep calling the server again and again to compare against every page?  Can you please plan to add an endpoint for it, it will be much faster, thank you

**Comment by renatonascalves** [comment]
Could you elaborate more on ,what, and how, you are trying to do?

If you have an app, for example, that lists the threads of a user, why would you need to check if a thread/message was already created for another specific user unrelated to the current user?

> Can you please plan to add an endpoint for it, it will be much faster, thank you

It'd be good to know what problem this is solving. We definitely can't add new endpoints to support specific features for everyone. A first look tells me this is something you should create yourself instead of bundling into BuddyPress but I'm curious about what and how you are trying to do it.

**Comment by ranfen** [comment]
> Could you elaborate more on ,what, and how, you are trying to do?

> If you have an app, for example, that lists the threads of a user, why would you need to check if a thread/message was already created for another specific user unrelated to the current user?

**Normal case**
You are right, in the normal case we do not need to know if a user messaged another user, when I build a message's inbox ill just get all the threads and list them all in the inbox if there are any. That's works great. 


> It'd be good to know what problem this is solving. We definitely can't add new endpoints to support specific features for everyone. A first look tells me this is something you should create yourself instead of bundling into BuddyPress but I'm curious about what and how you are trying to do it.

**Second case**
The problem that will be solved is:
 let's say I'm logged as a user and browsing the activities then I wanted to message someone privately, ill create a message button under that user profile it will open new layout with text field input where I can write my message to him

but before I load the messaging layout I would like to check if I messaged this person before or not, if never messaged him before ill show blank layout and a text field where I can write my first message
But if I messaged that user before, I would like to get the thread messages list the history of messages, so I can read all my previous messages to him then I can send more messages 

I hope my explanation is clear

thank you

**Comment by renatonascalves** [comment]
It looks like you want a new field on the [member schema](https://developer.buddypress.org/bp-rest-api/reference/members/#schema), similar to the `friendship_status` but checking if a user has a thread with the current logged in user.

**Comment by renatonascalves** [comment]
Since you would: get the activities and the user related to the activity (including this new field with the "status" of the user, meaning if they have a thread with the current logged-in user.)

**Comment by imath** [comment]
To my understanding it looks more like a "filter by recipient's user ID" messages need. This means, we'd need to edit `BP_Messages_Thread::get_current_threads_for_user()` to add an `include` parameter to pass recipient ids and then add a `"r IN {$includes)" clause there https://github.com/buddypress/buddypress/blob/master/src/bp-messages/classes/class-bp-messages-thread.php#L732

**Comment by ranfen** [comment]
If you guys approved this and implement it please let us know, thanks

**Comment by renatonascalves** [comment]
Related ticket: https://buddypress.trac.wordpress.org/ticket/9157

**Comment by renatonascalves** [comment]
@imath I'd like a second opinion on this one.

Your suggestion to use `"r.user_id IN {$includes)"` doesn't quite work here, because we need to get the threads not only from the recipients passed, but also we need to check if those recipients threads are associated with the current logged in user. That's how we know if they messaged each other. I came up with two possible SQL queries.

This one uses another INNER JOIN:

```sql
SELECT
	m.thread_id,
	MAX(m.date_sent) AS date_sent
FROM
	wp_bp_messages_recipients r
	INNER JOIN wp_bp_messages_recipients r2 ON r.thread_id = r2.thread_id
	INNER JOIN wp_bp_messages_messages m ON m.thread_id = r.thread_id
WHERE
	r.is_deleted = 0
	AND r.user_id = 1 <-- this is the current logged user or user_id passed
	AND r2.user_id IN (2, 3) <-- this is the array of recipient ids
	AND r.sender_only = 0
GROUP BY
	m.thread_id
ORDER BY
	date_sent DESC
LIMIT 0,
10;
```

This one uses a subquery to perform this task:

```sql

SELECT
    m.thread_id,
    MAX(m.date_sent) AS date_sent
FROM
    wp_bp_messages_recipients r
INNER JOIN wp_bp_messages_messages m ON m.thread_id = r.thread_id
WHERE
    r.is_deleted = 0
    AND r.sender_only = 0
    AND r.user_id = 1  <-- this is the current logged user or user_id passed
    AND r.thread_id IN (
        SELECT thread_id
        FROM wp_bp_messages_recipients
        WHERE user_id in (2, 3) <-- this is the array of recipient ids
    )
GROUP BY
    m.thread_id
ORDER BY
    date_sent DESC
LIMIT 0, 10;
```

I wonder if you have a preference here.

**Comment by imath** [comment]
Thanks for digging more into it @renatonascalves 

I prefer the 2nd one 😄 

So the `$include` new parameter would be used to generate this part of the Query:

```sql
AND r.thread_id IN (
        SELECT thread_id
        FROM wp_bp_messages_recipients
        WHERE user_id in (2, 3) <-- this is the array of recipient ids
)
```

**Comment by renatonascalves** [comment]
@imath Awesome. Just a note that I haven't noticed any performance difference between the two SQL queries. I'll implement using the 2nd one. :)

**Comment by renatonascalves** [comment]
@ranfen In case you are curious, here is the initial implementation: https://github.com/buddypress/buddypress/pull/394

^ this goes to your "Second case" example. :)

**Comment by renatonascalves** [comment]
Feature introduced here: https://buddypress.trac.wordpress.org/changeset/14069
