### ISSUE TITLE
activity display name

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#458]
Hi 
can you please add the activity creator display name to the activities list returned, i know we have the user id, but making a call  for each activity to get the user display name its really not good idea

 thank you

![image4](https://user-images.githubusercontent.com/80561800/192607807-adc695eb-4e0f-476c-bbba-b99d0a487087.png)

**Comment by renatonascalves** [comment]
@imath What do you think?

**Comment by renatonascalves** [comment]
The user ID is `embeddable` so they could get the display name of the user without actually making a second request directly.

**Comment by imath** [comment]
@renatonascalves They couldn't get the activity author's display name actually, we need to add the `embed` context to the name property of the Members endpoint schema to completely satisfy @ranfen need. See #459

**Comment by ranfen** [comment]
thank you guys
just want to add that the` _embed=true` works but only works for admin, we want the display name, author of the activity we are building and android app an having the author name will help us a lot
the rest api is amazing just we missing some things and this api will support mobile apps 

![iScreen Shoter - 20221003095608031](https://user-images.githubusercontent.com/80561800/193596210-78a2a4e5-2b2a-4424-b64b-51cb57ef3f81.jpg)
