### ISSUE TITLE
Status/Roadmap/Contributing?

### ISSUE THREAD

**Issue by lougreenwood** [buddypress/BP-REST#46]
Hi,

What's the status of the project, seems it's not seen much activity recently? I have a requirement for BP REST support in my project, so if there's any planned roadmap or way for me to contribute it would be good to know.

Thanks in advance - I understand it's hard to get traction for this kind of project early on :)

**Comment by dalemugford** [comment]
I feel the same way— really think BuddyPress with a rest API makes it far more flexible and modern.

**Comment by lougreenwood** [comment]
Yep, my use case is a completely headless WP installation (SPA UI client), so personally, REST is a top priority for me...

**Comment by dalemugford** [comment]
Similar for me WordPress is being used for an application. I have written some of my own custom endpoints to do a couple things, but officially baked support would be much better!

**Comment by lougreenwood** [comment]
I think we may end up having to go down a similar route of custom endpoints too - I wonder how many more people are doing the same because of lack of official direction. Seems a waste of energy when it will all need implementing again officially…

**Comment by renatonascalves** [comment]
Status and roadmaps can be seen here: https://github.com/buddypress/BP-REST/projects/1
For contributions here: https://github.com/buddypress/BP-REST/blob/master/CONTRIBUTING.md

I'm happy to answer any questions and help as much as possible. :)
