### ISSUE TITLE
Adapt the BP REST API to BP Rewrites

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#479]
`bp_core_get_user_domain()` has been deprecated in BuddyPress 12.0, see https://buddypress.trac.wordpress.org/changeset/13433

**Comment by renatonascalves** [comment]
@imath It looks like we are not using this function anymore here. And it was updated in previosu commits, does that mean this issue can be resolved?

**Comment by imath** [comment]
Yes I think we're all good!
