### ISSUE TITLE
The sitewide notice endpoint is not documented

### ISSUE THREAD

**Issue by imath** [buddypress/BP-REST#481]
After checking [developer.buddypress.org](https://developer.buddypress.org), I noticed this endpoint was missing into our documentation.

**Comment by renatonascalves** [comment]
@imath I know you are planning on some changes here for this milestone. Should we wait before adding documentation about it?

**Comment by imath** [comment]
Hi @renato yes I think it’s safer, we’ll have a better idea in 2 weeks I believe 👍

imath
https://imathi.eu
________________________________
De : Renato Alves ***@***.***>
Envoyé : Tuesday, March 5, 2024 12:25:15 PM
À : buddypress/BP-REST ***@***.***>
Cc : imath ***@***.***>; Mention ***@***.***>
Objet : Re: [buddypress/BP-REST] The sitewide notice endpoint is not documented (Issue #481)


@imath<https://github.com/imath> I know you are planning on some changes here for this milestone. Should we wait before adding documentation about it?

**Comment by renatonascalves** [comment]
@imath Could you review this page?

`https://developer.buddypress.org/wp-admin/post.php?post=1685&action=edit`

**Comment by imath** [comment]
Hi @renatonascalves thanks for your work on it, It's ready to be published. We might need to update soon. But it's fine the way it is for now.

**Comment by renatonascalves** [comment]
Done: https://developer.buddypress.org/bp-rest-api/reference/private-messaging/sitewide-notices/
