### ISSUE TITLE
Groups Endpoint always returns 0 for total_member_count

### ISSUE THREAD

**Issue by GForceWeb** [buddypress/BP-REST#484]
I always get a value of zero from the API when polling a group.

If I change the following though, I get the correct values

class-bp-rest-groups-endpoint.php:736

Change From:
`'total_member_count' => 0,`
To:
`'total_member_count' => groups_get_total_member_count($item->id),`

Is there a reason I'm missing why value is set to 0?

**Comment by renatonascalves** [comment]
Could you share a sample of the request? For easier confirmation of the bug.

**Comment by GForceWeb** [comment]
> Could you share a sample of the request? For easier confirmation of the bug.

I'm sending requests to `/wp-json/buddypress/v1/groups` and both requests with no URL parameters along with requests with a variety of URL parameters such as `?show_hidden=true&page=1&type=popular` all return `0` for `total_member_count` with the default BuddyPress 11.2.0 plugin.

If I modify the code as per my original post I do get correct member counts

**Comment by renatonascalves** [comment]
Yeah! I think you are using the view context and not using the `populate_extras` param. This data is not public by default in BuddyPress, so we tried to follow the same principle in its API.
