### ISSUE TITLE
Get all messages api is not working for non-admin role

### ISSUE THREAD

**Issue by sanjay-vv** [buddypress/BP-REST#493]
/buddyboss/v1/messages?user_id=2903&?box=inbox

can somebody check why this api is only working  for admin role users not for other users

**Comment by imath** [comment]
Hi, please report this to the BuddyPress fork you are using.

Our endpoint is not the one you shared but `/buddypress/...`

**Comment by sanjay-vv** [comment]
so where i need to connect for this issue?

**Comment by imath** [comment]
To the place where you downloaded this fork. Would you ask Apple for a Microsoft issue? It's the first endpoint part of your initial message.
