### ISSUE TITLE
How to save specific profile data for checkbox field type. 

### ISSUE THREAD

**Issue by SEN-RAD** [buddypress/BP-REST#494]
The docs only cover a basic example where: 

{
        "context": "edit",
        "value": "First value, Second value"
}

This works fine for simple POST requests with field_types like "textbox" or "number" but doesn't seem to be the appropriate format for "checkbox types" and the information in the docs is a little bit vague, it only specifies that value must be a string, and says:
"Depending on the field type, the field value can be stored in database as a serialized array or as a regular string. For example: in the case of a checkbox the user can select multiple options."

No examples are provided for different situations. I can see in the data structure and in the database, that "checkbox" values are stored as serialized strings, e.g.:

a:6{i:0;s:8:"Historie";i:1;s:8:"Politika";i:2;s:2:"TV";i:3;s:5:"Filmy";i:4;s:6:"Literatura";}

So I figured this should work:

{
        "context": "edit",
        "value": "a:3:{i:0;s:7:\"Aerobic\";i:1;s:8:\"Atletika\";i:2;s:9:\"Basketbal\";}"
    
}

But it doesn't, neither does the unserialized version ("Aerobic, Atletika, Basketbal" like "First value, Second value" ) The response doesn't throw an error, it returns this:

{
        "id": someId,
        "field_id": theID if the field I'm interested in,
        "user_id": my user ID,
        "value": {
            "raw": "a:0:{}",
            "unserialized": [],
            "rendered": "unimportant for now"></a></p>\n"
        },

What gets written in the database is "a:0:{}", either if there was nothing there before or if there were already some values. I have tried different options but can't seem to find the correct format. 

Could you please provide an example of how to save specific profile data for checkbox types?
Thank you so much.

**Comment by renatonascalves** [comment]
I'll update the documentation with examples for this use case.

**Comment by renatonascalves** [comment]
Actually, we already have an example on the doc: https://developer.buddypress.org/bp-rest-api/reference/extended-profiles/profile-data/#example-of-use-2

If you have a checkbox field with the following values: "Aerobic, Atletika, Basketbal". You can update them as such:

```
bp.apiRequest( {
  path: 'buddypress/v1/xprofile/6/data/1',
  type: 'POST',
  data: {
    context: 'edit',
    value: 'Aerobic,Atletika' <--- you can pass noe value or several with comma.
  }
} ).done( function( data ) {
  return data;
} ).fail( function( error ) {
  return error;
} );
```

The value will be saved serialized, as you've surmised. 

Am I correct that you did that and you got "a:0:{}" written to the database? If so, could you share more information about the request?
