### ISSUE TITLE
class-bp-rest-activity-endpoint.php review

### ISSUE THREAD

**Issue by paulgibbs** [buddypress/BP-REST#58]
I took a quick read of the file. I haven't tested the endpoint yet. Overall, I'm very impressed by the high standards of the code. I've found a few things that could use a opinion on to see whether we can make improvements:

From this version of the file: https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L183
 * Use `number_format_i18n( $size )` for translation.
 * Also, "image size" -- do we mean "image width" or height?

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L169
 * For Description, let's copy what WordPress used for `post_parent`? --> "The ID for the parent of the object." ?

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L499
 * For this complicated statement -- if you can get it all on one line and the width is about ~120 characters, do it. If you prefer it on multiple lines, if you move the final `{` down onto the next line, it'll be more readable that it is a conditional clause.

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L498
 * General question about the `empty( $id )` pattern (not specific to this line!).. If the variable is an array, or if the value isn't explicitly set, then I can see why you might check with `empty()` instead of checking for a false value (e.g. `! $id`). Can you explain to me, why, given on line 490 you set the value, you chose to wrote like this?

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L637
 * I'd rather we rely on `get_current_user_id()` rather than BuddyPress' user ID functions. Those date back to WPMU days, and we shouldn't use them for information about the current logged-in user.

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L770
https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L1044
 * Please no multi-line ternaries. :)

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L891
 * Is there any way to get the latest version number of the users endpoint from WordPress core?

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L918
 * I think super admins will pass the subsequent `bp_current_user_can( 'bp_moderate' )` check, this might not be needed.

https://github.com/buddypress/BP-REST/blob/09b205494bc085059555a760ee779311f7468b78/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L938
 * If the Groups component is active, I don't think `$bp->groups->id` will be set. Worth double-checking! :)

**Comment by renatonascalves** [comment]
- Avatar: Proper avatar support was added. Feedback welcome here: https://github.com/buddypress/BP-REST/commit/b6dad434458b21097eceb9c2b582426ac5f3cb1b

- Description: Updated!

> For this complicated statement
It will be more readable but it will not pass WPCS tests. And it can't be on one line because it has more than 120 chars.

> Can you explain to me, why, given on line 490 you set the value, you chose to wrote like this?
The value schema set it as an int. I'm just sanitizing to make sure the value is not empty and it is an int.

> I'd rather we rely on get_current_user_id() rather than BuddyPress' us...
Me too. But upon further testing, `get_current_user_id()` is not reliable. Not returning the current user. More info here: https://wordpress.slack.com/archives/C02RQBYUG/p1513187013000352

> Please no multi-line ternaries. :)
I kind of like them! But removed! :)

> Is there any way to get the latest version number of the users endpoint from WordPress core?
I did a minor search on the WP API code base and couldn't find a way so far.

> I think super admins will pass the subsequent bp_current_user_can( 'bp_moderate' ) check, t
Upon further testing, this only works if the admin is added the cap. When it is not, the check fails for admins. So I'll keep it.

> If the Groups component is active...
I borrow that logic from here: `bp_activity_screen_single_activity_permalink()`. The logic implies that's not the case if the component is active.
Also on `bp_has_activities()` you can see `groups->id` being used after a` bp_is_group()` conditionals.

**Comment by paulgibbs** [comment]
> It will be more readable but it will not pass WPCS tests. And it can't be on one line because it has more than 120 chars.

So change the WPCS standards. They're mostly crap, anyway. I'd rather have readable code, not someone else's opinion of what correct looks like.

**Comment by paulgibbs** [comment]
> Upon further testing, this only works if the admin is added the cap. When it is not, the check fails for admins. So I'll keep it.

Keep it consistent with what BP does in similar situations; if it makes an explicit super_admin check, then keep it, otherwise, don't.

**Comment by paulgibbs** [comment]
> If the Groups component is active...

Sorry, I wrote my comment the wrong way around. I meant originally, if the Groups component was *disabled*... :)

**Comment by paulgibbs** [comment]
>> Can you explain to me, why, given on line 490 you set the value, you chose to wrote like this?
> The value schema set it as an int. I'm just sanitizing to make sure the value is not empty and it is an int.

Have you proven that the REST API plumbing returns an empty value in this case? I don't think it does and I think `empty()` should only be used where the value tested is an array - or testing if a property on an array, or object, is set.

**Comment by renatonascalves** [comment]
Code review suggestions introduced! Closing for now! Thank you @paulgibbs :)
