### ISSUE TITLE
Can you please help me how to find the xprofile and message from using the given files.

### ISSUE THREAD

**Issue by virajsonagra** [buddypress/BP-REST#63]
I have included all the classes to my Wordpress site. Now, I want to get all those details like all profile data and message of my friends. What would be my endpoint and how does it get all the details.

Thank You.

**Comment by renatonascalves** [comment]
Here is a link with information of how to use a REST API: https://developer.wordpress.org/rest-api/using-the-rest-api/

The Xprofile and Messages endpoints are: `/xprofile/fields/{id}`

**Comment by renatonascalves** [comment]
I'm closing as this is a support question instead of a bug in the plugin. :)

**Comment by virajsonagra** [comment]
Thank You so much for your quick response. 
Sorry that I have posted as a bug.
Still, i am getting route not found error.
wp-json/xprofile

**Comment by renatonascalves** [comment]
The correct endpoint path is `wp-json/buddypress/v1/messages/`.

**Comment by virajsonagra** [comment]
I have tried that too. same message.

**Comment by renatonascalves** [comment]
I'd recommend trying to see the log. I have a local version working here.

**Comment by virajsonagra** [comment]
okay. so is there any other way that I can find the xprofile data?
I mean by wordpress query.

**Comment by renatonascalves** [comment]
I recommend you take a look at the code base and see how to fetch it. BuddyPress has an extensive API for this sort of thing. ?)
