### ISSUE TITLE
Rest Invalid Param

### ISSUE THREAD

**Issue by virtualLast** [buddypress/BP-REST#64]
GET request to https://development.myquestrian.com/wp-json/buddypress/v1/groups?group_type=eventing 

returns error
`{
"code": "rest_invalid_param",
"message": "Invalid parameter(s): group_type",
"data": {
"status": 400,
"params": {
"group_type": "group_type is not one of eventing, recreationalriding, stablesandyards, horsecare, competitiveriding."
}
}
}`

Not really sure why I am receiving this error - have I not formatted the URL correctly??

**Comment by renatonascalves** [comment]
@virtualLast Thank you for bringing this bug to my attention. I added a fix just not for this particular bug.
https://github.com/buddypress/BP-REST/commit/6a300cff4c854141c7100733ff20d71ba0b98c5a

Be aware that the group endpoint is not fully unit tests yet, so changes might occur in the future and it is not working completely.

:)

**Comment by renatonascalves** [comment]
Use the master branch for the lastest and recent changes.
