### ISSUE TITLE
Get Members returns only one result

### ISSUE THREAD

**Issue by virtualLast** [buddypress/BP-REST#65]
Title says it all really - I have 26 accounts created, are wp_users different from buddypress members??

I expected `/wp-json/buddypress/v1/members` to return 26 objects

**Comment by renatonascalves** [comment]
@virtualLast Thanks! Fixed this issue here: https://github.com/buddypress/BP-REST/commit/a5baa5108fbc4cccd9d82c5fa7bfd34a04c62c8f
