### ISSUE TITLE
Can mark all notifications as read

### ISSUE THREAD

**Issue by baconbro** [buddypress/BP-REST#68]
Add post support for mark notification as read. To enable multiple function one parametter of the request should be **post_type.**
Then depending of the post type the endpoint could trigger multiple functions.
Ex: 
if $resquest[post_type] = 'markallread' then bp_notifications_mark_notifications_from_user();
if $resquest[post_type] = 'addnotification' then bp_add_notification();

**Comment by renatonascalves** [comment]
@baconbro Could you elaborate a little bit what you are trying to accomplish here?
