### ISSUE TITLE
Where I can found documentation of available endpoints with detail?

### ISSUE THREAD

**Issue by patidarkishor777** [buddypress/BP-REST#83]
Where I can found documentation of available endpoints with detail?

**Comment by renatonascalves** [comment]
@patidarkishor777 Right now we don't have a documentation showing in details the commands. If you wanna know which components have support, you can [see](https://github.com/buddypress/BP-REST/blob/master/README.md).

**Comment by patidarkishor777** [comment]
Thanks Renato for your quick response.
Yes I can see available components but I didn't found an list if parameter
that api except,endpoint and authentication required for api call.

Could you provide me a way to get above info?

**Comment by renatonascalves** [comment]
If you are talking examples of how to use it, we still don't have that.

You'd need to see the code on the available components. You can also find in the endpoint schema the parameters used.

If you are not familiar with the REST API, here is a doc that will help you to get started.

https://developer.wordpress.org/rest-api/using-the-rest-api/
