### ISSUE TITLE
Add a basic documentation

### ISSUE THREAD

**Issue by mecanographik** [buddypress/BP-REST#90]
Hi,
Please enrich the readme file and give a minimum of information about the way to use and access to the BP REST API's end points. For example:
How to access to the Groups Endpoint (What is the rest Route), etc...

I have figured it out that the access is like :
https://mywebsite.com/wp-json/buddypress/v1

to get groups :
https://mywebsite.com/wp-json/buddypress/v1/groups

and so on...

but please explain in a doc the method, for example, to create a group via the BP REST API

nb: i'm using JWT Authentication for WP-API plugin to be able to add, delete posts, etc...
Does it work with the BP REST API the same way?
  
Thanks 😁

**Comment by renatonascalves** [comment]
I added the endpoint base paths to the readme... You can see which params are available for usage on each endpoint.

If you are new to the REST API world, maybe the WordPress code rest api documentation might be a good place to start: https://developer.wordpress.org/rest-api/using-the-rest-api/
