### ISSUE TITLE
Cannot specify all group stati

### ISSUE THREAD

**Issue by tannerm** [buddypress/BP-REST#94]
The default groups status is `public`. Because the type is string I am unable to query all group stati. Can we either change this to an array or remove the default?

**Comment by renatonascalves** [comment]
@tannerm Changed added here: https://github.com/buddypress/BP-REST/commit/3588313f77ba5b7a340b809d5d2e58e3ec18b55c

Thanks for the suggestion. :)

**Comment by tannerm** [comment]
Super, thanks!
