### ISSUE TITLE
Filter/action strategy

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/BP-REST#98]
The hook pattern in the `get_items()` methods is to put a `rest_{component}_get_items` hook at the end of the method, just before the `$response` is returned:

https://github.com/buddypress/BP-REST/blob/258f6cafba1186cece0cc29db16f30374f5f6ce3/includes/bp-activity/classes/class-bp-rest-activity-endpoint.php#L169

By comparison, the pattern in core endpoints is to filter the arguments passed to the query. See https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php?marks=261#L248, https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php?marks=236#L219

In neither case is it possible for developers to (directly) filter the items returned by the query function.

What's the best strategy here? IMO, a `do_action()` hook at the end of the method is not too useful - better would be to pass the query results through `apply_filters()`. But perhaps this is a pattern that we don't want to recommend, since it can wreck things like pagination. What do we think of emulating WP endpoints and putting filters only on the query args?

**Comment by renatonascalves** [comment]
@boonebgorges I agree adding the query result is not a good idea. I believe the core example is a good and useful one. I added an implemention adding something similar.

I do like the `do_action` hook at the end, so if you don't feel strongly about it, I'd like to keep it.

**Comment by boonebgorges** [comment]
Agreed. Sounds good.
